### ISSUE TITLE
WebUI doesn't start

### ISSUE THREAD

**Issue by Tenzix** [oobabooga/text-generation-webui#1007]
Hi i get this error when i run your start-webui or installer.
```
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: A:\AI\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary A:\AI\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Found the following quantized model: models\anon8231489123_vicuna-13b-GPTQ-4bit-128g\vicuna-13b-4bit-128g.safetensors
Loading model ...
A:\AI\oobabooga-windows\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
A:\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
A:\AI\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Press any key to continue...
```
Then when I press a nkey the console closes and nothing happens.
I installed

1. and reinstalled Anaconda
2. pycharm
3. Conda
4. Tensorflow
5. Nvidia drivers 

Now I don't know where to turn to move forward in my debug
![Capture](https://user-images.githubusercontent.com/58316083/230921594-fe5ad9a4-795b-4ff6-839f-b3251c3a64d5.PNG)

Thanks for your reading/help

**Comment by bbecausereasonss** [comment]
Seems related > https://github.com/oobabooga/text-generation-webui/issues/984

**Comment by fastjacksonmin** [comment]
Hi, @Tenzix. Not sure if you are able to fix this issue? I think I encountered the same issue as you when using the model anon8231489123_vicuna-13b-GPTQ-4bit-128g. (Same warning messages, followed by "press any key to continue...". 

I tried to uninstall and install the transformers as suggested in the discussion of #984. But got no luck. 

Also, when I tried to load another model, (--model facebook_opt-350m), I am actually able to start the webui without issue. I can also interact with the model. So not sure if the issue is specific to the particular model anon8231489123_vicuna-13b-GPTQ-4bit-128g. 
Thanks!

**Comment by sarfarazh** [comment]
Same Issue WebUI doesn't start. Tried all options

**Comment by mannuramesh** [comment]
Text generation web ui (oogabooga) sometimes does not generate text and it keeps on recursive as processing or AI is typing, especially I'm using Llama 2 7B q5 K M gguf model, but one thing i noticed, i reloaded the character in parameter section, then it started the text generation......... I think some one have to document these and fixe these bugs as soon as possible, i have screenshot for it too!

[IMG-20231013-WA0003.jpg](https://github.com/oobabooga/text-generation-webui/assets/93306452/0958d06d-8f4b-4436-bb3d-5cb104c84fbc)
