### ISSUE TITLE
I can't seem to get it to work. This is what I get every time.

### ISSUE THREAD

**Issue by BurnedP** [oobabooga/text-generation-webui#1048]
### Describe the bug

So, I've been trying to get this to work for some time now. I can't seem to get it working. I have a Ryzen 3600XT and an RTX 2060 Super, 16gigs of RAM and 8gigs of VRAM. Any input? It doesn't even generate one answer. I understand it to be a problem with video memory, but auto devices is enabled as well as disk, so shouldn't it well fit within the VRAM and RAM? Also, if cpu is enabled as a parameter, is lamma.cpp installed by default? Or do I have to do something else?

Model: gpt4-x-alpaca-13b-native-4bit-128g

Error:

```
Traceback (most recent call last):
  File "C:\Tools\OogaBooga\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\Tools\OogaBooga\text-generation-webui\modules\text_generation.py", line 234, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 243, in forward
    attn_output = self.o_proj(attn_output)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 420, in forward
    x = x.float()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 8.00 GiB total capacity; 7.07 GiB already allocated; 0 bytes free; 7.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 3.41 seconds (0.00 tokens/s, 0 tokens, context 44, seed 137123083)
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I just run the web ui as normal and when I try to generate anything, this comes up.

### Logs

```shell
Traceback (most recent call last):
  File "C:\Tools\OogaBooga\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "C:\Tools\OogaBooga\text-generation-webui\modules\text_generation.py", line 234, in generate_with_callback
    shared.model.generate(**kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 243, in forward
    attn_output = self.o_proj(attn_output)
  File "C:\Tools\OogaBooga\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Tools\OogaBooga\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 420, in forward
    x = x.float()
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.00 MiB (GPU 0; 8.00 GiB total capacity; 7.07 GiB already allocated; 0 bytes free; 7.31 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Output generated in 3.41 seconds (0.00 tokens/s, 0 tokens, context 44, seed 137123083)
```

### System Info

```shell
Windows 11, AMD Ryzen 3600XT, NVIDIA RTX 2060 Super, 16Gb RAM, 8Gb VRAM
```

**Comment by Iceayydev** [comment]
you can follow the low vram guide in the wiki, its what worked for me and others.

**Comment by unterumarmung** [comment]
> you can follow the low vram guide in the wiki, its what worked for me and others.

Can you please send a link?

**Comment by jllllll** [comment]
`--auto-devices` does not work for GPTQ-quantized models. You need to use `--pre_layer` for those. In your case, I would recommend `--pre_layer 32`

**Comment by VitaliyAT** [comment]
I have the same problem on 1080 8 vram

**Comment by StingrayA** [comment]
> `--auto-devices` does not work for GPTQ-quantized models. You need to use `--pre_layer` for those. In your case, I would recommend `--pre_layer 32`

where to put this exactly?

**Comment by jllllll** [comment]
> > `--auto-devices` does not work for GPTQ-quantized models. You need to use `--pre_layer` for those. In your case, I would recommend `--pre_layer 32`
> 
> where to put this exactly?

`webui.py` The latest version has a spot for it towards the top of the file.
If you are on an older version, it should be around line 167.
