### ISSUE TITLE
Bitsandbytes can't find my cuda installation

### ISSUE THREAD

**Issue by cometbus** [oobabooga/text-generation-webui#1068]
### Describe the bug

Warning: --cai-chat is deprecated. Use --chat instead.
Detected Windows CUDA installation at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_121.dll
C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py:118: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Detected Windows CUDA installation at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_121.dll
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Setup Failed!
Detected Windows CUDA installation at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_121.dll
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Setup Failed!
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ E:\git\vicuna\oobabooga-windows\text-generation-webui\server.py:18 in <module>                   │
│                                                                                                  │
│    15 from PIL import Image                                                                      │
│    16                                                                                            │
│    17 import modules.extensions as extensions_module                                             │
│ >  18 from modules import api, chat, shared, training, ui                                        │
│    19 from modules.html_generator import chat_html_wrapper                                       │
│    20 from modules.LoRA import add_lora_to_model                                                 │
│    21 from modules.models import load_model, load_soft_prompt, unload_model                      │
│                                                                                                  │
│ E:\git\vicuna\oobabooga-windows\text-generation-webui\modules\training.py:12 in <module>         │
│                                                                                                  │
│     9 import torch                                                                               │
│    10 import transformers                                                                        │
│    11 from datasets import Dataset, load_dataset                                                 │
│ >  12 from peft import (LoraConfig, get_peft_model, get_peft_model_state_dict,                   │
│    13 │   │   │   │     prepare_model_for_int8_training)                                         │
│    14                                                                                            │
│    15 from modules import shared, ui                                                             │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\__init__.py:22 in <module>   │
│                                                                                                  │
│   19                                                                                             │
│   20 __version__ = "0.2.0"                                                                       │
│   21                                                                                             │
│ > 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_    │
│   23 from .peft_model import (                                                                   │
│   24 │   PeftModel,                                                                              │
│   25 │   PeftModelForCausalLM,                                                                   │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\mapping.py:16 in <module>    │
│                                                                                                  │
│    13 # See the License for the specific language governing permissions and                      │
│    14 # limitations under the License.                                                           │
│    15                                                                                            │
│ >  16 from .peft_model import (                                                                  │
│    17 │   PeftModel,                                                                             │
│    18 │   PeftModelForCausalLM,                                                                  │
│    19 │   PeftModelForSeq2SeqLM,                                                                 │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\peft_model.py:31 in <module> │
│                                                                                                  │
│    28 from transformers.modeling_outputs import SequenceClassifierOutput, TokenClassifierOutpu   │
│    29 from transformers.utils import PushToHubMixin                                              │
│    30                                                                                            │
│ >  31 from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder               │
│    32 from .utils import (                                                                       │
│    33 │   TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,                              │
│    34 │   WEIGHTS_NAME,                                                                          │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\tuners\__init__.py:20 in     │
│ <module>                                                                                         │
│                                                                                                  │
│   17 # See the License for the specific language governing permissions and                       │
│   18 # limitations under the License.                                                            │
│   19                                                                                             │
│ > 20 from .lora import LoraConfig, LoraModel                                                     │
│   21 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizatio    │
│   22 from .prefix_tuning import PrefixEncoder, PrefixTuningConfig                                │
│   23 from .prompt_tuning import PromptEmbedding, PromptTuningConfig, PromptTuningInit            │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\tuners\lora.py:36 in         │
│ <module>                                                                                         │
│                                                                                                  │
│    33                                                                                            │
│    34                                                                                            │
│    35 if is_bnb_available():                                                                     │
│ >  36 │   import bitsandbytes as bnb                                                             │
│    37                                                                                            │
│    38                                                                                            │
│    39 @dataclass                                                                                 │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\__init__.py:6 in     │
│ <module>                                                                                         │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ >  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\autograd\_functions. │
│ py:5 in <module>                                                                                 │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ >   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\functional.py:15 in  │
│ <module>                                                                                         │
│                                                                                                  │
│     12 from typing import Tuple                                                                  │
│     13 from torch import Tensor                                                                  │
│     14                                                                                           │
│ >   15 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     16 from functools import reduce  # Required in Python 3                                      │
│     17                                                                                           │
│     18 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py:135 in │
│ <module>                                                                                         │
│                                                                                                  │
│   132 │   if lib is None and torch.cuda.is_available():                                          │
│   133 │   │   CUDASetup.get_instance().generate_instructions()                                   │
│   134 │   │   CUDASetup.get_instance().print_log_stack()                                         │
│ > 135 │   │   raise RuntimeError('''                                                             │
│   136 │   │   CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs ab   │
│   137 │   │   If you cannot find any issues and suspect a bug, please open an issue with detal   │
│   138 │   │   https://github.com/TimDettmers/bitsandbytes/issues''')                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

NA

### Logs

```shell
Warning: --cai-chat is deprecated. Use --chat instead.
Detected Windows CUDA installation at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_121.dll
C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py:118: UserWarning: WARNING: No GPU detected! Check your CUDA paths. Proceeding to load CPU-only library...
  warn(msg)
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
Detected Windows CUDA installation at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_121.dll
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Setup Failed!
Detected Windows CUDA installation at C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1
CUDA SETUP: WARNING! libcuda.so not found! Do you have a CUDA driver installed? If you are on a cluster, make sure you are on a CUDA machine!
CUDA SETUP: CUDA runtime path found: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin\cudart64_121.dll
CUDA SETUP: Required library version not found: libbitsandbytes_cpu.so. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes.so...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
================================================================================

CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
CUDA SETUP: Setup Failed!
CUDA SETUP: Problem: The main issue seems to be that the main CUDA library was not detected.
CUDA SETUP: Solution 1): Your paths are probably not up-to-date. You can update them via: sudo ldconfig.
CUDA SETUP: Solution 2): If you do not have sudo rights, you can do the following:
CUDA SETUP: Solution 2a): Find the cuda library via: find / -name libcuda.so 2>/dev/null
CUDA SETUP: Solution 2b): Once the library is found add it to the LD_LIBRARY_PATH: export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:FOUND_PATH_FROM_2a
CUDA SETUP: Solution 2c): For a permanent solution add the export from 2b into your .bashrc file, located at ~/.bashrc
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ E:\git\vicuna\oobabooga-windows\text-generation-webui\server.py:18 in <module>                   │
│                                                                                                  │
│    15 from PIL import Image                                                                      │
│    16                                                                                            │
│    17 import modules.extensions as extensions_module                                             │
│ >  18 from modules import api, chat, shared, training, ui                                        │
│    19 from modules.html_generator import chat_html_wrapper                                       │
│    20 from modules.LoRA import add_lora_to_model                                                 │
│    21 from modules.models import load_model, load_soft_prompt, unload_model                      │
│                                                                                                  │
│ E:\git\vicuna\oobabooga-windows\text-generation-webui\modules\training.py:12 in <module>         │
│                                                                                                  │
│     9 import torch                                                                               │
│    10 import transformers                                                                        │
│    11 from datasets import Dataset, load_dataset                                                 │
│ >  12 from peft import (LoraConfig, get_peft_model, get_peft_model_state_dict,                   │
│    13 │   │   │   │     prepare_model_for_int8_training)                                         │
│    14                                                                                            │
│    15 from modules import shared, ui                                                             │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\__init__.py:22 in <module>   │
│                                                                                                  │
│   19                                                                                             │
│   20 __version__ = "0.2.0"                                                                       │
│   21                                                                                             │
│ > 22 from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_    │
│   23 from .peft_model import (                                                                   │
│   24 │   PeftModel,                                                                              │
│   25 │   PeftModelForCausalLM,                                                                   │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\mapping.py:16 in <module>    │
│                                                                                                  │
│    13 # See the License for the specific language governing permissions and                      │
│    14 # limitations under the License.                                                           │
│    15                                                                                            │
│ >  16 from .peft_model import (                                                                  │
│    17 │   PeftModel,                                                                             │
│    18 │   PeftModelForCausalLM,                                                                  │
│    19 │   PeftModelForSeq2SeqLM,                                                                 │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\peft_model.py:31 in <module> │
│                                                                                                  │
│    28 from transformers.modeling_outputs import SequenceClassifierOutput, TokenClassifierOutpu   │
│    29 from transformers.utils import PushToHubMixin                                              │
│    30                                                                                            │
│ >  31 from .tuners import LoraModel, PrefixEncoder, PromptEmbedding, PromptEncoder               │
│    32 from .utils import (                                                                       │
│    33 │   TRANSFORMERS_MODELS_TO_PREFIX_TUNING_POSTPROCESS_MAPPING,                              │
│    34 │   WEIGHTS_NAME,                                                                          │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\tuners\__init__.py:20 in     │
│ <module>                                                                                         │
│                                                                                                  │
│   17 # See the License for the specific language governing permissions and                       │
│   18 # limitations under the License.                                                            │
│   19                                                                                             │
│ > 20 from .lora import LoraConfig, LoraModel                                                     │
│   21 from .p_tuning import PromptEncoder, PromptEncoderConfig, PromptEncoderReparameterizatio    │
│   22 from .prefix_tuning import PrefixEncoder, PrefixTuningConfig                                │
│   23 from .prompt_tuning import PromptEmbedding, PromptTuningConfig, PromptTuningInit            │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\peft\tuners\lora.py:36 in         │
│ <module>                                                                                         │
│                                                                                                  │
│    33                                                                                            │
│    34                                                                                            │
│    35 if is_bnb_available():                                                                     │
│ >  36 │   import bitsandbytes as bnb                                                             │
│    37                                                                                            │
│    38                                                                                            │
│    39 @dataclass                                                                                 │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\__init__.py:6 in     │
│ <module>                                                                                         │
│                                                                                                  │
│    3 # This source code is licensed under the MIT license found in the                           │
│    4 # LICENSE file in the root directory of this source tree.                                   │
│    5                                                                                             │
│ >  6 from .autograd._functions import (                                                          │
│    7 │   MatmulLtState,                                                                          │
│    8 │   bmm_cublas,                                                                             │
│    9 │   matmul,                                                                                 │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\autograd\_functions. │
│ py:5 in <module>                                                                                 │
│                                                                                                  │
│     2 import warnings                                                                            │
│     3                                                                                            │
│     4 import torch                                                                               │
│ >   5 import bitsandbytes.functional as F                                                        │
│     6                                                                                            │
│     7 from dataclasses import dataclass                                                          │
│     8 from functools import reduce  # Required in Python 3                                       │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\functional.py:15 in  │
│ <module>                                                                                         │
│                                                                                                  │
│     12 from typing import Tuple                                                                  │
│     13 from torch import Tensor                                                                  │
│     14                                                                                           │
│ >   15 from .cextension import COMPILED_WITH_CUDA, lib                                           │
│     16 from functools import reduce  # Required in Python 3                                      │
│     17                                                                                           │
│     18 # math.prod not compatible with python < 3.8                                              │
│                                                                                                  │
│ C:\Users\Samson\AppData\Roaming\Python\Python310\site-packages\bitsandbytes\cextension.py:135 in │
│ <module>                                                                                         │
│                                                                                                  │
│   132 │   if lib is None and torch.cuda.is_available():                                          │
│   133 │   │   CUDASetup.get_instance().generate_instructions()                                   │
│   134 │   │   CUDASetup.get_instance().print_log_stack()                                         │
│ > 135 │   │   raise RuntimeError('''                                                             │
│   136 │   │   CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs ab   │
│   137 │   │   If you cannot find any issues and suspect a bug, please open an issue with detal   │
│   138 │   │   https://github.com/TimDettmers/bitsandbytes/issues''')                             │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs aboveto fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```

### System Info

```shell
Windows 10
```

**Comment by jllllll** [comment]
I'm assuming that you manually installed? bitsandbytes does not support Windows by default. I compiled a custom Windows version, but it is specifically for cuda 11.7.
https://github.com/jllllll/bitsandbytes-windows-webui/raw/main/bitsandbytes-0.37.2-py3-none-any.whl

**Comment by himansharma21** [comment]
I ran into a similar issue. I fixed it by following the guide at: https://rentry.org/llama-tard-v2#bonus-3-4bit-llama-basic-setup

Scroll down to `Install bitsandbytes for 8bit support (skip this on Linux)`.
