### ISSUE TITLE
Chat AI Mode won't work after last patsches today

### ISSUE THREAD

**Issue by elcotek** [oobabooga/text-generation-webui#1111]
### Describe the bug

Chat AI Mode won't work after last patsches today

after I update, i get this error if try start talking to the bot

CUDA SETUP: CUDA runtime path found: E:\one-click-installers-oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 218, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 144, in chatbot_wrapper
    prompt = generate_chat_prompt(text, state, **kwargs)
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 42, in generate_chat_prompt
    while i >= 0 and len(encode(''.join(rows))[0]) < max_length:
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Chat AI Mode won't work after last patsches today

after I update, i got this error if try start talking to the bot

CUDA SETUP: CUDA runtime path found: E:\one-click-installers-oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 218, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 144, in chatbot_wrapper
    prompt = generate_chat_prompt(text, state, **kwargs)
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 42, in generate_chat_prompt
    while i >= 0 and len(encode(''.join(rows))[0]) < max_length:
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)

### Logs

```shell
CUDA SETUP: CUDA runtime path found: E:\one-click-installers-oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\routes.py", line 393, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 1108, in process_api
    result = await self.call_function(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\blocks.py", line 929, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\one-click-installers-oobabooga-windows\installer_files\env\lib\site-packages\gradio\utils.py", line 490, in async_iteration
    return next(iterator)
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 218, in cai_chatbot_wrapper
    for history in chatbot_wrapper(text, state):
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 144, in chatbot_wrapper
    prompt = generate_chat_prompt(text, state, **kwargs)
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\chat.py", line 42, in generate_chat_prompt
    while i >= 0 and len(encode(''.join(rows))[0]) < max_length:
  File "E:\one-click-installers-oobabooga-windows\text-generation-webui\modules\text_generation.py", line 31, in encode
    input_ids = shared.tokenizer.encode(str(prompt), return_tensors='pt', add_special_tokens=add_special_tokens)
```

### System Info

```shell
RTX 2080 8GB, 32GB Rizen 7 3700
```

**Comment by elcotek** [comment]
Ok i found out, i have to load the model manuelly for now in the model settings, after the server  has started <-- Thats not a good change, i think the load routine is missing/not implemented or a bug

**Comment by Sprysin** [comment]
> Check ooba's post on reddit. He mentioned something about making it not necessary to go through command-line parameters and improve the UI experience. Perhaps, a fix should be to load a default model it can find in the folder like Automatic1111's
> 
> https://www.reddit.com/r/Oobabooga/comments/12jxw0p/new_models_tab/

I see what you mean however I am not given the prompt to select a model, is there an alternative location that I can go to launch the program through the model?

**Comment by elcotek** [comment]
All right, i use the --model option for now. This solved my problem.

**Comment by Remowylliams** [comment]
> All right, i use the --model option for now. This solved my problem.

There is a --model-menu now if you don't have a model hard coded into your startup
