### ISSUE TITLE
Server.py start-up error with "Torch not compiled with CUDA enabled"

### ISSUE THREAD

**Issue by x3onkait** [oobabooga/text-generation-webui#15]
I had finished the installation progress without any notable errors and warnings, but I face an unexpected error when I execute the command `python server.py` even though I installed PyTorch and related packages at step 3 in the installation procedure.

Do you have any ideas? Here are my environment specification and error log. I'm trying to run `pygmalion` model with your project.

**spec**
```
(I'm using laptop)
CPU : 12th Gen Intel(R) Core(TM) i9-12900H
RAM : 64GB
Disk : 1TB SSD / 2TB SSD
GPU : Intel(R) Iris(R) Xe Graphics / NVIDIA GeForce RTX 3080 Laptop GPU (TGP 150W)
```
**Error log**

```
(textgen) PS D:\PygmalionProj\text-generation-webui> python server.py
Loading pygmalion-6b...
Traceback (most recent call last):
  File "D:\PygmalionProj\text-generation-webui\server.py", line 211, in <module>
    model, tokenizer = load_model(model_name)
  File "D:\PygmalionProj\text-generation-webui\server.py", line 78, in load_model
    model = AutoModelForCausalLM.from_pretrained(Path(f"models/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.float16).cuda()
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

In my case, NVIDIA Cuda compiler driver has been installed successfully.
```
(textgen) PS D:\PygmalionProj\text-generation-webui> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

But when I check if `torch.cuda.is_available()` prints `True` that means cuda is in operation, it prints `False` even though every required packages has been installed completely.
```
(textgen) PS D:\PygmalionProj\text-generation-webui> python
Python 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.is_available()
False
```

Do you have any ideas about what I have to do to solve this problem and run `text-generation-webui` properly? 
And any help related to these would be thankful!

**Comment by Chosen-one-Vault13** [comment]
I had the same problem, for two reasons:
1 - I didn't have CUDA 11.7 installed, I had older versions.
2 - I accidentally installed the cpu version pytorch the first time, then tried to install the gpu version on top of it. Uninstalling pytorch and reinstalling the correct version fixed the problem.

**Comment by oobabooga** [comment]
@x3onkait, it could or could not work with an older pytorch version, but I haven't tested. 

Could you try creating a new conda environment with pytorch-cuda 11.7 using the commands in the README to see if it works?

**Comment by x3onkait** [comment]
@oobabooga OK, I'll try to make it again with the installation guide.

**Comment by x3onkait** [comment]
@oobabooga The same error occurs even though I tried completely again.

```
(textgen) PS C:\textgenerationwebui\text-generation-webui> conda install pytorch torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia
Collecting package metadata (current_repodata.json): done
Solving environment: done

# All requested packages already installed.

(textgen) PS C:\textgenerationwebui\text-generation-webui> python server.py
Loading pygmalion-6b...
Traceback (most recent call last):
  File "C:\textgenerationwebui\text-generation-webui\server.py", line 211, in <module>
    model, tokenizer = load_model(model_name)
  File "C:\textgenerationwebui\text-generation-webui\server.py", line 78, in load_model
    model = AutoModelForCausalLM.from_pretrained(Path(f"models/{model_name}"), low_cpu_mem_usage=True, torch_dtype=torch.float16).cuda()
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 749, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 641, in _apply
    module._apply(fn)
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 664, in _apply
    param_applied = fn(param)
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 749, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\3NR1QUE\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 221, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
(textgen) PS C:\textgenerationwebui\text-generation-webui>
```

But it seems that the installed CUDA version is accurately `11.7`.
```
(textgen) PS C:\textgenerationwebui\text-generation-webui> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Jun__8_16:59:34_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.99
Build cuda_11.7.r11.7/compiler.31442593_0
```

(I run on this Windows 11 PRO, with `pygmalion-6b` model.)

**Comment by x3onkait** [comment]
Every time I installed and retried the procedure on `README.md`, I faced the same potential warnings like below:

(installation command on Conda virtual environment)
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia
```
(output)
```
(textgen) PS C:\textgenerationwebui> conda install pytorch torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
```
(But I can install every required packages successfully after those.)

Could these generate the CUDA error what I'm struggling?

**Comment by oobabooga** [comment]
I haven't experienced this issue before, but one thing to try is installing the CUDA toolkit directly from NVIDIA: https://developer.nvidia.com/cuda-downloads

**Comment by x3onkait** [comment]
I already installed both CUDA toolkits version 11.7 and 12.0 via NVIDIA's official website, but it didn't seem to be working properly in the conda virtual environment. Maybe there are some points making errors beyond my knowledge.

(*Currently I'm using an alternative, KoboldAI + TavernAI instead, but it perfectly works for me unless I don't exceed the amount of VRAM of my graphic card.*)

**Comment by oobabooga** [comment]
Pytorch installation is something beyond the scope of this web ui, so I will close this issue.

In any case, if someone can find a solution to the problems above, please write a comment below.

**Comment by Slug-Cat** [comment]
I solved this problem by running: 
conda install torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia
instead of 
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 git -c pytorch -c nvidia
