### ISSUE TITLE
The installed version of bitsandbytes was compiled without GPU support & AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by zelnie** [oobabooga/text-generation-webui#1969]
### Describe the bug

I've been searching to fix these two issues I keep getting when I run start_windows.bat; `The installed version of bitsandbytes was compiled without GPU support` and `AssertionError: Torch not compiled with CUDA enabled`. Any help is appreciated, thanks,

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Downloaded current version of Windows one-click installer
2. Install for NVIDIA system.
3. Selected do not download model since I downloaded a couple before hand
4. Ran start_windows.bat

### Logs

```shell
INFO:Gradio HTTP request redirected to localhost :)
bin C:\Users\SJ\Documents\textgen\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
C:\Users\SJ\Documents\textgen\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
The following models are available:

1. pygmalion-1.3b
2. pygmalion-6b_dev-4bit-128g

Which one do you want to load? 1-2

1

INFO:Loading pygmalion-1.3b...
Traceback (most recent call last):
  File "C:\Users\SJ\Documents\textgen\oobabooga_windows\text-generation-webui\server.py", line 921, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\SJ\Documents\textgen\oobabooga_windows\text-generation-webui\modules\models.py", line 90, in load_model
    model = model.cuda()
  File "C:\Users\SJ\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\SJ\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\SJ\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\SJ\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\SJ\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\Users\SJ\AppData\Roaming\Python\Python310\site-packages\torch\cuda\__init__.py", line 239, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

Done!
Press any key to continue . . .
```

### System Info

```shell
Windows 10
Nvidia RTX 2060 Super
```

**Comment by jllllll** [comment]
Seems that it is attempting to use a Torch package that was installed outside of the webui's virtual environment.
Try adding this just after `@rem fix failed install when installing to a separate drive` in `start_windows.bat`:
```
SET "CONDA_SHLVL="
SET PYTHONNOUSERSITE=1
SET "PYTHONPATH="
```
If that doesn't work, open `cmd_windows.bat`, enter `python -m torch.utils.collect_env` and post the output.

**Comment by zelnie** [comment]
> Seems that it is attempting to use a Torch package that was installed outside of the webui's virtual environment. Try adding this just after `@rem fix failed install when installing to a separate drive` in `start_windows.bat`:
> 
> ```
> SET "CONDA_SHLVL="
> SET PYTHONNOUSERSITE=1
> SET "PYTHONPATH="
> ```
> 
> If that doesn't work, open `cmd_windows.bat`, enter `python -m torch.utils.collect_env` and post the output.



I tried it and a new error appears, telling me I am missing aiofiles. I tried `pip install aiofiles` but it told me I already had it, so I ran `start_windows.bat` again, but the same error persists.
```
Traceback (most recent call last):
  File "C:\Users\SJ\Documents\textgen\oobabooga_windows\text-generation-webui\server.py", line 21, in <module>
    import gradio as gr
  File "C:\Users\SJ\Documents\textgen\oobabooga_windows\installer_files\env\lib\site-packages\gradio\__init__.py", line 3, in <module>
    import gradio.components as components
  File "C:\Users\SJ\Documents\textgen\oobabooga_windows\installer_files\env\lib\site-packages\gradio\components.py", line 24, in <module>
    import aiofiles
ModuleNotFoundError: No module named 'aiofiles'
```

So, since that didnt work, I ran `python -m torch.utils.collect_env` and here's the output. I have the feeling that I might need to reinstall CUDA.
```
(C:\Users\SJ\Documents\textgen\oobabooga_windows\installer_files\env) C:\Users\SJ\Documents\textgen\oobabooga_windows>python -m torch.utils.collect_env
Collecting environment information...
PyTorch version: 2.0.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060 SUPER
Nvidia driver version: 531.61
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3600
Name=AMD Ryzen 7 3700X 8-Core Processor
ProcessorType=3
Revision=28928

Versions of relevant libraries:
[pip3] lion-pytorch==0.0.6
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] pytorch-lightning==1.9.0
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h8bd8f75_46356
[conda] mkl-service               2.4.0           py310h2bbff1b_1
[conda] mkl_fft                   1.3.6           py310h4ed8f06_1
[conda] mkl_random                1.2.2           py310h4ed8f06_1
[conda] numpy                     1.24.3          py310h055cbcc_1
[conda] numpy-base                1.24.3          py310h65a83cf_1
[conda] pytorch                   2.0.0           py3.10_cuda11.7_cudnn8_0    pytorch
[conda] pytorch-cuda              11.7                 h16d0643_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0                    pypi_0    pypi
[conda] torchvision               0.15.0                   pypi_0    pypi
```

**Comment by jllllll** [comment]
That is just plain bizarre. It says that you have the cpu version installed, but then at the end states that you have the gpu version. I guess that, somehow, the gpu version is incorrectly reporting itself as being cpu-only. Open `cmd_windows.bat` and run this command:
```
python -m pip install https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp310-cp310-win_amd64.whl --force-reinstall
```
If that doesn't help, then I honestly don't know how to fix it. Maybe a full reinstall, along with ensuring you have the latest gpu drivers? As far as the CUDA Toolkit is concerned, the installer installs a copy of it into the Conda environment.
Adding `SET "CUDA_PATH=%INSTALL_ENV_DIR%"` to `start_windows.bat` should ensure that the correct cuda is used. That said, your log states that it is already using the correct version of cuda.

**Comment by zelnie** [comment]
> That is just plain bizarre. It says that you have the cpu version installed, but then at the end states that you have the gpu version. I guess that, somehow, the gpu version is incorrectly reporting itself as being cpu-only. Open `cmd_windows.bat` and run this command:
> 
> ```
> python -m pip install https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp310-cp310-win_amd64.whl --force-reinstall
> ```
> 
> If that doesn't help, then I honestly don't know how to fix it. Maybe a full reinstall, along with ensuring you have the latest gpu drivers? It does say that you have a pretty recent driver.
> 
> As far as the CUDA Toolkit is concerned, the installer installs a copy of it into the Conda environment. Adding `SET "CUDA_PATH=%INSTALL_ENV_DIR%"` to `start_windows.bat` should ensure that the correct cuda is used. That said, your log states that it is already using the correct version of cuda.

Running `python -m pip install https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp310-cp310-win_amd64.whl --force-reinstall` as well as adding  `SET "CUDA_PATH=%INSTALL_ENV_DIR%"` to `start_windows.bat` has fixed the issue. The webui starts with zero errors, thanks!

**Comment by H41907** [comment]
> ha

Many thanks for this. Was looking for a while for a solution to this issue and this solved it for me.

**Comment by H41907** [comment]
> h



> That is just plain bizarre. It says that you have the cpu version installed, but then at the end states that you have the gpu version. I guess that, somehow, the gpu version is incorrectly reporting itself as being cpu-only. Open `cmd_windows.bat` and run this command:
> 
> ```
> python -m pip install https://download.pytorch.org/whl/cu117/torch-2.0.0%2Bcu117-cp310-cp310-win_amd64.whl --force-reinstall
> ```
> 
> If that doesn't help, then I honestly don't know how to fix it. Maybe a full reinstall, along with ensuring you have the latest gpu drivers? It does say that you have a pretty recent driver.
> 
> As far as the CUDA Toolkit is concerned, the installer installs a copy of it into the Conda environment. Adding `SET "CUDA_PATH=%INSTALL_ENV_DIR%"` to `start_windows.bat` should ensure that the correct cuda is used. That said, your log states that it is already using the correct version of cuda.

Many thanks for this. Was looking for a while for a solution to this issue and this solved it for me.
