### ISSUE TITLE
PYTORCH_CUDA_ALLOC_CONF

### ISSUE THREAD

**Issue by seandennis** [oobabooga/text-generation-webui#2179]
### Describe the bug

I have a GTX1070 with 8gb vram. I had heaps of problems with nothing installing and had to do a pip install everything. now I have everything installed I get this error when running start_windows.bat.

return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 8.00 GiB total capacity; 6.75 GiB already allocated; 0 bytes free; 6.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Followed Aitrepreneur's youtube video https://youtu.be/lb_lC4XFedU . I had troubles, as it wouldn't run and had heaps of errors. I removed all my python versions (uninstalled), downloaded pytorch from website to get cuda 11.7 both conda and pip and miniconda3. still had errors. opened cmd in oobabooga_windows\text-generation-webui> file location. did python server.py , it ran the python file and got error after error, so I did a pip install of all packages. then ran start-windows.bat and now I get this error.

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 8.00 GiB total capacity; 6.75 GiB already allocated; 0 bytes free; 6.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Logs

```shell
WARNING:More than one .pt model has been found. The last one will be selected. It could be wrong.
INFO:Found the following quantized model: models\anon8231489123_gpt4-x-alpaca-13b-native-4bit-128g\gpt-x-alpaca-13b-native-4bit-128g.pt
Traceback (most recent call last):
  File "U:\oobabooga\oobabooga_windows\text-generation-webui\server.py", line 984, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "U:\oobabooga\oobabooga_windows\text-generation-webui\modules\models.py", line 95, in load_model
    output = load_func(model_name)
  File "U:\oobabooga\oobabooga_windows\text-generation-webui\modules\models.py", line 272, in GPTQ_loader
    model = modules.GPTQ_loader.load_quantized(model_name)
  File "U:\oobabooga\oobabooga_windows\text-generation-webui\modules\GPTQ_loader.py", line 199, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "C:\Users\Stocker\miniconda3\lib\site-packages\transformers\modeling_utils.py", line 1878, in to
    return super().to(*args, **kwargs)
  File "C:\Users\Stocker\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\Stocker\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\Stocker\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 820, in _apply
    param_applied = fn(param)
  File "C:\Users\Stocker\miniconda3\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 314.00 MiB (GPU 0; 8.00 GiB total capacity; 6.75 GiB already allocated; 0 bytes free; 6.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
Intel Core i7-6700 CPU @ 3.40GHz
32GB Ram
EVGA GeForce GTX1070 8GB
Windows 10 Pro
```

**Comment by RoARene317** [comment]
Out of memory is indeed out of memory on your GPU. Try to use --gpu-memory if you are out of memory.

**Comment by Soalire** [comment]
> Out of memory is indeed out of memory on your GPU. Try to use --gpu-memory to limit GPU memory usage if you are out of memory. For in this case , GTX 1070 8G , you should allocate around 6500 MB.

sorry, where do i put that command?

**Comment by Simplegram** [comment]
> > Out of memory is indeed out of memory on your GPU. Try to use --gpu-memory to limit GPU memory usage if you are out of memory. For in this case , GTX 1070 8G , you should allocate around 6500 MB.
> 
> sorry, where do i put that command?

Put it in your webui.py file. Find `def run_model()` function and change the flags inside `run_cmd()`. In your case it should be
```
def run_model():
    os.chdir("text-generation-webui")
    run_cmd("python server.py --chat --gpu-memory 6500", environment=True)  # put your flags here!
```
or if you want to use MiB
```
def run_model():
    os.chdir("text-generation-webui")
    run_cmd("python server.py --chat --gpu-memory 6500MiB", environment=True)  # put your flags here!
```

You can also add more flags as shown below. You can find more at [https://github.com/oobabooga/text-generation-webui#basic-settings](url)
```
def run_model():
    os.chdir("text-generation-webui")
    run_cmd("python server.py --chat --xformers --bf16 --gpu-memory 6500MiB --wbits 4 --groupsize 128", environment=True)
```

**Comment by cocobeach** [comment]
Quick question the amount of Vram allocated is a proportion of what is free? I have 2x Nvidia RTX A4000 what would be the best configuration to make the most of both cards and both VRams?
With the current default it only uses 30% of one card, but it is really really slow too.

**Comment by seandennis** [comment]
> > > Out of memory is indeed out of memory on your GPU. Try to use --gpu-memory to limit GPU memory usage if you are out of memory. For in this case , GTX 1070 8G , you should allocate around 6500 MB.
> > 
> > 
> > sorry, where do i put that command?
> 
> Put it in your webui.py file located inside the same folder as `start_windows.bat`. ![image](https://user-images.githubusercontent.com/34500695/239515790-fd14c0b0-49ee-428b-b976-ca261a1a72e2.png)
> 
> Find `def run_model()` function and change the flags inside `run_cmd()`. In your case it should be
> 
> ```
> def run_model():
>     os.chdir("text-generation-webui")
>     run_cmd("python server.py --chat --gpu-memory 6500", environment=True)  # put your flags here!
> ```
> 
> or if you want to use MiB
> 
> ```
> def run_model():
>     os.chdir("text-generation-webui")
>     run_cmd("python server.py --chat --gpu-memory 6500MiB", environment=True)  # put your flags here!
> ```
> 
> You can also add more flags as shown below. You can find more at https://github.com/oobabooga/text-generation-webui#basic-settings
> 
> ```
> def run_model():
>     os.chdir("text-generation-webui")
>     run_cmd("python server.py --chat --xformers --bf16 --gpu-memory 6500MiB --wbits 4 --groupsize 128", environment=True)
> ```

Thankyou Simplegram, I ran the first one that you suggested and it worked.

this is the one that I used.
run_cmd("python server.py --chat --gpu-memory 6500", environment=True)  # put your flags here!

**Comment by Simplegram** [comment]
> > > > Out of memory is indeed out of memory on your GPU. Try to use --gpu-memory to limit GPU memory usage if you are out of memory. For in this case , GTX 1070 8G , you should allocate around 6500 MB.
> > > 
> > > 
> > > sorry, where do i put that command?
> > 
> > 
> > Put it in your webui.py file located inside the same folder as `start_windows.bat`. ![image](https://user-images.githubusercontent.com/34500695/239515790-fd14c0b0-49ee-428b-b976-ca261a1a72e2.png)
> > Find `def run_model()` function and change the flags inside `run_cmd()`. In your case it should be
> > ```
> > def run_model():
> >     os.chdir("text-generation-webui")
> >     run_cmd("python server.py --chat --gpu-memory 6500", environment=True)  # put your flags here!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or if you want to use MiB
> > ```
> > def run_model():
> >     os.chdir("text-generation-webui")
> >     run_cmd("python server.py --chat --gpu-memory 6500MiB", environment=True)  # put your flags here!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also add more flags as shown below. You can find more at https://github.com/oobabooga/text-generation-webui#basic-settings
> > ```
> > def run_model():
> >     os.chdir("text-generation-webui")
> >     run_cmd("python server.py --chat --xformers --bf16 --gpu-memory 6500MiB --wbits 4 --groupsize 128", environment=True)
> > ```
> 
> Thankyou Simplegram, I ran the first one that you suggested and it worked.
> 
> this is the one that I used. run_cmd("python server.py --chat --gpu-memory 6500", environment=True) # put your flags here!

Glad to hear that! Happy to help :)
