### ISSUE TITLE
RWKV new model mode - CUDA illegal memory access

### ISSUE THREAD

**Issue by dblacknc** [oobabooga/text-generation-webui#2316]
### Describe the bug

I can apparently load the new RWKV model format (pytorch .bin files) no problem.  When I try to chat, after a few seconds two CUDA illegal memory access errors are seen, and the UI must be restarted.

I've tried both --auto-devices by itself, and no --auto-devices, but --load-in-8bit.   The latter gives a different error, but I read there's already an issue about loading RWKV in 8 bit.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Start the UI with --auto-devices and load RWKV_rwkv-raven-7b.
It appears to successfully load into the GPUs.  Then I enter something in the chat box and hit enter.   After a few seconds:

Traceback (most recent call last):
  File "/root/text-generation-webui/modules/callbacks.py", line 73, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/root/text-generation-webui/modules/text_generation.py", line 277, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1565, in generate
    return self.sample(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2612, in sample
    outputs = self(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 770, in forward
    rwkv_outputs = self.rwkv(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 660, in forward
    hidden_states, state, attentions = block(
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 390, in forward
    feed_forward, state = self.feed_forward(self.ln2(hidden), state=state)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 358, in forward
    key = torch.square(torch.relu(self.key(key)))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-3 (gentask):
Traceback (most recent call last):
  File "/root/miniconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/root/text-generation-webui/modules/callbacks.py", line 80, in gentask
    clear_torch_cache()
  File "/root/text-generation-webui/modules/callbacks.py", line 112, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

### Logs

```shell
In repro section
```

### System Info

```shell
ubuntu 22.04 updated this week
2 x RTX3060 12GB
git pull this morning + pip install -r requirements --upgrade
```

**Comment by yhyu13** [comment]
@dblacknc 

It appears to be hg transformer's adpation to rwkv that throw the error:

File "/root/miniconda3/envs/textgen/lib/python3.10/site-packages/transformers/models/rwkv/modeling_rwkv.py", line 358, in forward
key = torch.square(torch.relu(self.key(key)))
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

Would you like to test RWKV on its repo which uses transformer? Is it working fine there?

**Comment by dblacknc** [comment]
This seems to work now - closing
