### ISSUE TITLE
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

### ISSUE THREAD

**Issue by mindcz** [oobabooga/text-generation-webui#274]
Hi guys,
First of all thank you for your work.
I had tried to setup webui and its starts fine. But any request to generate ends with the same error.
Any ideas how to fix it?
![image](https://user-images.githubusercontent.com/127721505/224625381-a6f97d8c-a52d-4f64-9c57-80368a97f892.png)

**Comment by mindcz** [comment]
even after few successful phrases it fall down with the same error
![image](https://user-images.githubusercontent.com/127721505/224669614-99fe57f1-6ff9-499d-b49c-923763b7ecd4.png)

**Comment by oobabooga** [comment]
Those are two different errors. I don't know what the first is, but the second means that your GPU ran out of memory.

**Comment by oobabooga** [comment]
It is now possible to set fractional `--gpu-memory` values too like `--gpu-memory 3400MiB`.

**Comment by RaymondTracer** [comment]
None of the suggestions are working for me, I still get the same error as OP.

**Comment by LoganDark** [comment]
Same here. Using LLaMA-7B

![image](https://user-images.githubusercontent.com/4723091/227844189-4c7584cb-d96e-4bd6-9d79-0fee072599ff.png)

and whenever I try to generate anything:

![image](https://user-images.githubusercontent.com/4723091/227844287-584faacb-aa8f-48b4-a92b-b8ac82a71704.png)

the entire GPU crashes and I get this error:

![image](https://user-images.githubusercontent.com/4723091/227844348-904285ff-bdd2-46d1-8546-f3d480fa3d1a.png)

I have `--gpu-memory` set to 8 with 12GB of VRAM

**Comment by LoganDark** [comment]
mine was caused by a too-high memory overclock, nice

**Comment by mindcz** [comment]
I had reinstalled new version and now its wont start at all
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.
Traceback (most recent call last):
  File "C:\Distr\oobabooga-windows\text-generation-webui\server.py", line 18, in <module>
    from modules import chat, shared, training, ui, api
  File "C:\Distr\oobabooga-windows\text-generation-webui\modules\chat.py", line 15, in <module>
    from modules.html_generator import (fix_newlines, chat_html_wrapper,
  File "C:\Distr\oobabooga-windows\text-generation-webui\modules\html_generator.py", line 12, in <module>
    import markdown
ModuleNotFoundError: No module named 'markdown'
Press any key to continue . . .

**Comment by oobabooga** [comment]
Try replacing your install.bat with the updated one and re-running it https://github.com/oobabooga/one-click-installers/

**Comment by RaymondTracer** [comment]
After the update I get

```
Warning: torch.cuda.is_available() returned False.
This means that no GPU has been detected.
Falling back to CPU mode.
```

**Comment by mindcz** [comment]
> Try replacing your install.bat with the updated one and re-running it https://github.com/oobabooga/one-click-installers/

for now its new problem) I have conda installed And nothing was changed from my side
but  now i Cant runt install
![image](https://user-images.githubusercontent.com/127721505/230843701-43852e75-d396-4eb2-b138-3eef5bf76d27.png)

**Comment by RandomLegend** [comment]
I have the same error (the 1st one) CUBLAS_STATUS_NOT_INITIALIZED when trying to launch a LLama Model.

**Comment by yhyu13** [comment]
@ALL I was having this error when launching multiple instances of LLM on GPU. If running textgen alone, I'm fine

**Comment by jtara1** [comment]
Does the project require a certain version of NVIDIA CUDA? I'm running 12.1. I'm getting the error trying a few 13B models, but not `TheBloke_vicuna-7B-1.1-GPTQ-4bit-128g`

**Comment by lorsonblair** [comment]
> Fixed this by reducing the VRAM with the `--gpu-memory` flag by one gigabyte.

Hi there, How did you reduce the memory with that command? Thanks.
