### ISSUE TITLE
torch.cuda.OutOfMemoryError, having troubles using the model on the ooga booga webui

### ISSUE THREAD

**Issue by Alexercer** [oobabooga/text-generation-webui#2873]
### Describe the bug

hello, this is my first time trying to use a model on my GPU or any more sophisticated text-generator aside from GPT itself, i have found a video on the topic and so i followed the instalation advice, but for some reason at a point it does not load as it does in the video and instead return an error, my files for the webui however seem to differ from the ones displayed at the video and because of this error im strugling to actually use the model, the videos in question were: https://youtu.be/cCQdzqAHcFk for the webui and: https://youtu.be/nVC9D9fRyNU for the alpaca model instalation, however at the moment i should open the aformationed model at the start_windows.bat file it instead results in a error

"bin C:\Modelooogabooga\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll
2023-06-25 20:56:15 INFO:Loading gpt4-x-alpaca-13b-native-4bit-128g...
2023-06-25 20:56:15 INFO:The AutoGPTQ params are: {'model_basename': 'gpt-x-alpaca-13b-native-4bit-128g-cuda', 'device': 'cuda:0', 'use_triton': False, 'inject_fused_attention': True, 'inject_fused_mlp': True, 'use_safetensors': False, 'trust_remote_code': False, 'max_memory': None, 'quantize_config': BaseQuantizeConfig(bits=4, group_size=128, damp_percent=0.01, desc_act=False, sym=True, true_sequential=True, model_name_or_path=None, model_file_base_name=None)}
2023-06-25 20:56:17 WARNING:The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Traceback (most recent call last):
  File "C:\Modelooogabooga\oobabooga_windows\text-generation-webui\server.py", line 1008, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Modelooogabooga\oobabooga_windows\text-generation-webui\modules\models.py", line 66, in load_model
    output = load_func_map[loader](model_name)
  File "C:\Modelooogabooga\oobabooga_windows\text-generation-webui\modules\models.py", line 272, in AutoGPTQ_loader
    return modules.AutoGPTQ_loader.load_quantized(model_name)
  File "C:\Modelooogabooga\oobabooga_windows\text-generation-webui\modules\AutoGPTQ_loader.py", line 55, in load_quantized
    model = AutoGPTQForCausalLM.from_quantized(path_to_model, **params)
  File "C:\Modelooogabooga\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\auto.py", line 82, in from_quantized
    return quant_func(
  File "C:\Modelooogabooga\oobabooga_windows\installer_files\env\lib\site-packages\auto_gptq\modeling\_base.py", line 773, in from_quantized
    accelerate.utils.modeling.load_checkpoint_in_model(
  File "C:\Modelooogabooga\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 1116, in load_checkpoint_in_model
    set_module_tensor_to_device(model, param_name, param_device, value=param, dtype=dtype)
  File "C:\Modelooogabooga\oobabooga_windows\installer_files\env\lib\site-packages\accelerate\utils\modeling.py", line 167, in set_module_tensor_to_device
    new_value = value.to(device)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 6.00 GiB total capacity; 5.31 GiB already allocated; 0 bytes free; 5.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Pressione qualquer tecla para continuar. . ."

the last line stands for "press any key to continue. . ." and i do not know what exactly went wrong or what i can do to fix it, i am very thankfull in advance for any help is much apreciated.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

I followed mostly the intalation described in the video exept when you try to use the start.bat file it returns the aforementioned error

### Screenshot

<img width="1280" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/111154338/6611c92d-4398-45e8-8ff6-51d59278de42">

### Logs

```shell
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 14.00 MiB (GPU 0; 6.00 GiB total capacity; 5.31 GiB already allocated; 0 bytes free; 5.36 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Pressione qualquer tecla para continuar. . .
```

### System Info

```shell
Processor: 12th Gen Intel(R) Core(TM) i7-12700H 2.30 GHz
Installed RAM: 16.0 GB (usable: 15.7 GB)
Device ID: B4131E24-BAA6-4339-A5E3-1F865751945E
Product ID: 00355-60755-36899-AAOEM
System Type: 64-bit operating system, x64-based processor
Pen and Touch: No pen or touch input is available for this display.

System: Currently windoes 11 

Brand: Avell

Computing device: desktop
```

**Comment by EliEron** [comment]
CUDA out of memory means pretty much what it says on the tin, CUDA (which is essentially used for GPU compute) ran out of memory while loading your model. CUDA makes use of VRAM. According to your error message your card only has 6GB of VRAM which is extremely low by text generation standards. Text models are **Really** large. And while GPTQ reduces the size of the model by about a quarter it still requires a ton of VRAM. For a 13b model you need at least a 10GB card, ideally a 12GB card.

A 7b model will in theory fit, though I can't guarantee it will work well, and 7b model aren't that amazing quality wise.

So GPU based models likely won't work well for you. With 16GB of System Memory you could give GGML (llama.cpp) models a try, they are mainly designed to run on your CPU, rather than GPU. That means they are way slower, but they don't require high VRAM to run.

**Comment by Alexercer** [comment]
> CUDA out of memory means pretty much what it says on the tin, CUDA (which is essentially used for GPU compute) ran out of memory while loading your model. CUDA makes use of VRAM. According to your error message your card only has 6GB of VRAM which is extremely low by text generation standards. Text models are **Really** large. And while GPTQ reduces the size of the model to a quarter of the full size it still requires a ton of VRAM. For a 13b model you need at least a 10GB card, ideally a 12GB card.
> 
> A 7b model will in theory fit, though I can't guarantee it will work well, and 7b model aren't that amazing quality wise.
> 
> So GPU based models likely won't work well for you. With 16GB of System Memory you could give GGML (llama.cpp) models a try, they are mainly designed to run on your CPU, rather than GPU. That means they are way slower, but they don't require high VRAM to run.

well that sucks, is it possible to use the CPU via oooga booga or even try to use a different GPU? i have a13,9GB GPU available tho i have no idea how to using it will impact the overall performance of the PC, is it possible to configure witch GPU to use?

<img width="572" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/111154338/8a9e4648-7da0-46b8-973d-787287c2c392">


it translates to use Dedicated GPU memory 
GPU memory and shared GPU memory
as well as temperature down below

<img width="157" alt="image" src="https://github.com/oobabooga/text-generation-webui/assets/111154338/0acdf0b6-f7b3-4b64-a9e9-4f41e25a6687">
should i change the GPU or will it be too much of an inpact to the performace of my machine? also thanks for the help in advance

**Comment by berkut1** [comment]
You have only 6 GB of VRAM, not 14 GB.
You can try to set GPU memory limit to 2GB or 3GB.
Or use a GGML model in CPU mode.

**Comment by Alexercer** [comment]
> You have only 6 GB of VRAM, not 14 GB. You can try to set GPU memory limit to 2GB or 3GB. Or use a GGML model in CPU mode.

well thats a shame, i suppose i shall delete the ooga booga as well as the model and try again with lhama.cpp, thanks for the advice!

**Comment by aSocialMenace** [comment]
The web ui used to give you an option to limit how vram you allow it to use and with that slider i was able to set mine to 68000mb and that worked for me using my rtx 2070 super. but after i updated oogabooga i lost that slider and now this model wont work for me at all

**Comment by LakshayDCoder** [comment]
Hi. 
Has anyone managed to solve this issue? I am running a 30b model on  RTX 4070 with 12GB of VRAM. Is there any way we can limit the vram requirements?

**Comment by berkut1** [comment]
@LakshayDCoder GGUF models support that.
