### ISSUE TITLE
One click installer doesn't work CUDA SETUP: CUDA detection failed! 

### ISSUE THREAD

**Issue by NovNovikov** [oobabooga/text-generation-webui#2960]
### Describe the bug

When I try to do a fresh install using the one click installer file "start_windows.bat" I get and error in the end.
The installation worked three days ago, but today I tried to update and it broke everything and the reinstallation doesn't help now.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Launch start_windows.bat and select NVIDIA.

### Logs

```shell
*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the bottom of the "Model" tab and download one.
*******************************************************************


bin L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda122.dll
False
CUDA SETUP: CUDA runtime path found: L:\AI_pictures_generate\oobabooga_windows\installer_files\env\bin\cudart64_12.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 122
CUDA SETUP: Required library version not found: libbitsandbytes_cuda122.dll. Maybe you need to compile it from source?
CUDA SETUP: Defaulting to libbitsandbytes_cpu.dll...

================================================ERROR=====================================
CUDA SETUP: CUDA detection failed! Possible reasons:
1. CUDA driver not installed
2. CUDA not installed
3. You have multiple conflicting CUDA libraries
4. Required library not pre-compiled for this bitsandbytes release!
CUDA SETUP: If you compiled from source, try again with `make CUDA_VERSION=DETECTED_CUDA_VERSION` for example, `make CUDA_VERSION=113`.
CUDA SETUP: The CUDA version for the compile might depend on your conda install. Inspect CUDA version via `conda list | grep cuda`.
================================================================================

CUDA SETUP: Something unexpected happened. Please compile from source:
git clone git@github.com:TimDettmers/bitsandbytes.git
cd bitsandbytes
CUDA_VERSION=122
python setup.py install
CUDA SETUP: Setup Failed!
Traceback (most recent call last):
  File "L:\AI_pictures_generate\oobabooga_windows\text-generation-webui\server.py", line 35, in <module>
    from modules import chat, loaders, presets, shared, training, ui, utils
  File "L:\AI_pictures_generate\oobabooga_windows\text-generation-webui\modules\training.py", line 18, in <module>
    from peft import (
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\peft\__init__.py", line 22, in <module>
    from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING, PEFT_TYPE_TO_CONFIG_MAPPING, get_peft_config, get_peft_model
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\peft\mapping.py", line 16, in <module>
    from .peft_model import (
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\peft\peft_model.py", line 34, in <module>
    from .tuners import (
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\__init__.py", line 21, in <module>
    from .lora import LoraConfig, LoraModel
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\peft\tuners\lora.py", line 41, in <module>
    import bitsandbytes as bnb
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\__init__.py", line 6, in <module>
    from . import cuda_setup, utils, research
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\research\__init__.py", line 1, in <module>
    from . import nn
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\research\nn\__init__.py", line 1, in <module>
    from .modules import LinearFP8Mixed, LinearFP8Global
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\research\nn\modules.py", line 8, in <module>
    from bitsandbytes.optim import GlobalOptimManager
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\optim\__init__.py", line 6, in <module>
    from bitsandbytes.cextension import COMPILED_WITH_CUDA
  File "L:\AI_pictures_generate\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py", line 20, in <module>
    raise RuntimeError('''
RuntimeError:
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

### System Info

```shell
Windows 10, RTX 4090, i5-13600kf, 64 gb ram ddr5
```

**Comment by jllllll** [comment]
Run `cmd_windows.bat` and post the output of this command: `conda list cuda`

At first glance, it seems that conda installed the 12.2 CUDA Toolkit, but this shouldn't have happened.

**Comment by jllllll** [comment]
I added CUDA 12.2 support to the Windows version of bitsandbytes. To install the updated version, run `cmd_windows.bat` and enter this command:
```
python -m pip install https://github.com/jllllll/bitsandbytes-windows-webui/releases/download/wheels/bitsandbytes-0.39.1-py3-none-win_amd64.whl --force-reinstall --no-deps
```

**Comment by NovNovikov** [comment]
Thanks, @jllllll, I entered the command and it works now!
