### ISSUE TITLE
API: [MPS DEVICE]: streaming vs block - block has a bug

### ISSUE THREAD

**Issue by MeinDeutschkurs** [oobabooga/text-generation-webui#3316]
### Describe the bug

on apple devices, it tries to complete through output.cuda() if the API is used to generate a block. (During streaming, everything works fine.)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

simply start the examples which are included in the repos API-examples. (and do not use —cpu flag, because we want mps-mode)

### Screenshot

It would just show that "torch is not compiled with cuda enabled"

### Logs

```shell
1) ERROR:
Starting streaming server at ws://0.0.0.0:7848/api/v1/stream
Starting API at http://0.0.0.0:7847/api
Running on local URL:  http://0.0.0.0:7846

To create a public link, set `share=True` in `launch()`.
Output generated in 5.06 seconds (3.56 tokens/s, 18 tokens, context 20, seed 295159361)
127.0.0.1 - - [25/Jul/2023 22:23:43] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/Users/jophi/Desktop/kira/3rd-party/text-generation-webui/modules/text_generation.py", line 285, in generate_reply_HF
    output = output.cuda()
  File "/Users/jophi/miniforge3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 258, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Output generated in 13.09 seconds (7.18 tokens/s, 94 tokens, context 94, seed 1519254890)
^[[1;2C127.0.0.1 - - [25/Jul/2023 22:29:16] "POST /api/v1/generate HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/Users/jophi/Desktop/kira/3rd-party/text-generation-webui/modules/text_generation.py", line 285, in generate_reply_HF
    #output = output.cuda()
  File "/Users/jophi/miniforge3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 258, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Output generated in 0.47 seconds (12.76 tokens/s, 6 tokens, context 94, seed 256227055)

2) ERROR WITH ADDED DEBUG INFO:

Starting streaming server at ws://0.0.0.0:7848/api/v1/stream
Starting API at http://0.0.0.0:7847/api
Running on local URL:  http://0.0.0.0:7846

To create a public link, set `share=True` in `launch()`.
127.0.0.1 - - [25/Jul/2023 22:35:18] "POST /api/v1/generate HTTP/1.1" 200 -
tensor([    1,  3575, 29915, 29872,   263,  8444, 20255, 29889,  3529,  1371,
          278,  1404,   408,  1781,   408,   366,   508, 29991,    13,    13,
         2659, 29901,   306,   508,  1074,   373,   385,  1967, 29901,   376,
        29909, 23852,   528,  2728,  2222,   767,   297,  1090,   705,   279,
         1213, 29889,  1317,   372, 13907,   363,   599,   278, 12990,   819,
          778, 29973,   897,  8204,   363,  3869,   470,  1939, 29889,  7370,
          596,  8908,   411,   376,  8241, 29892,   372,   338,  1213,   470,
          376,  3782, 29892,   372,  3508, 29915, 29873, 29908,   322,  5649,
          596, 10608, 29889,   319,  5405,  8178, 12241,  6824,  6824,    13,
           13,  7900, 22137, 29901,  3869, 29892,   372,   338, 29889,   450,
         3229,   376, 29909, 23852,   528,  2728,  2222,   767,   297,  1090,
          705,   279, 29908,   947,   451,  1712,   738,  1283,  6270,  4086,
          470,   589,   468,  7606,  4958,   393,   723,   367,   297,   932,
         6649,   403,   363,   599, 12990,   819,   778, 29889,   739,  3763,
        16612,   263,  2022,   591,  4362,  1067,  6046,   393,   338, 15574,
         6942,   411,   278,   365,  7210, 29911, 29984, 29974,  7881, 29889,
         1094,  1472,   408,   278,  3030,   310,   278,  1967,   338,  8210,
          322,  3390,  1319, 29892,   445,  3229,   881,   451,  4556,   738,
        10311,   470,  1283,  1947,   304,  5019, 29889,     2],
       device='mps:0')
Traceback (most recent call last):
  File "/Users/jophi/Desktop/kira/3rd-party/text-generation-webui/modules/text_generation.py", line 288, in generate_reply_HF
    output = output.cuda()
  File "/Users/jophi/miniforge3/envs/textgen/lib/python3.10/site-packages/torch/cuda/__init__.py", line 258, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Output generated in 13.34 seconds (7.05 tokens/s, 94 tokens, context 94, seed 1978642183)
^[[A^CTraceback (most recent call last):
  File "/Users/jophi/Desktop/kira/3rd-party/text-generation-webui/server.py", line 1179, in <module>
    time.sleep(0.5)

(I added some debug output to see the tensor-object)
```

### System Info

```shell
macOS, M2 Ultra, 192GB, full cores. Ventura (13.5)
```

**Comment by sweetcard** [comment]
I have the same issue too.

**Comment by sweetcard** [comment]
I have found the solution as following.
Modify the file _text_generation.py_ line **294** in _modules_ :
from:
`if cuda :`

TO:

`if cuda and torch.cuda.is_available():`
