### ISSUE TITLE
Error on inference with 70B and lora attached

### ISSUE THREAD

**Issue by St33lMouse** [oobabooga/text-generation-webui#3796]
### Describe the bug

Illegal memory access error when chatting with the model if a lora is attached. Works fine if there's no lora.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Load any 70B gptq model in exllama-HF, split memory 16,18

Attach any 70B lora. Message indicates attach successful.

Ask it anything, get the error. This does not happen if there's no lora attached--it works fine without a lora.

### Logs

```shell
Traceback (most recent call last):
  File "/home/mouse/text-generation-webui/modules/callbacks.py", line 56, in gentask
    ret = self.mfunc(callback=_callback, *args, **self.kwargs)
  File "/home/mouse/text-generation-webui/modules/text_generation.py", line 321, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 1633, in generate
    return self.sample(
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/transformers/generation/utils.py", line 2755, in sample
    outputs = self(
  File "/home/mouse/text-generation-webui/modules/exllama_hf.py", line 87, in __call__
    logits = self.ex_model.forward(torch.tensor([seq[-1:]], dtype=torch.long), ex_cache, lora=self.lora).to(input_ids.device)
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/exllama/model.py", line 967, in forward
    r = self._forward(input_ids[:, chunk_begin : chunk_end],
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/exllama/model.py", line 1051, in _forward
    hidden_states = _move_tensor(hidden_states, device, "hidden_states", self.config)
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/exllama/model.py", line 707, in _move_tensor
    tensor = tensor.to("cpu")
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Exception in thread Thread-5 (gentask):
Traceback (most recent call last):
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mouse/text-generation-webui/modules/callbacks.py", line 63, in gentask
    clear_torch_cache()
  File "/home/mouse/text-generation-webui/modules/callbacks.py", line 95, in clear_torch_cache
    torch.cuda.empty_cache()
  File "/home/mouse/anaconda3/envs/textgen/lib/python3.10/site-packages/torch/cuda/memory.py", line 133, in empty_cache
    torch._C._cuda_emptyCache()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### System Info

```shell
Current version of ubuntu, linux
2 x 3090
```

**Comment by St33lMouse** [comment]
> Gotta turn off fused attention for that.

Ah! sorry I said it was a bug. I got it to work on auto for GPTQ. A bit slower than exllama, but it works. I, uh, don't see any way to adjust max context length for auto for gptq. Am I stuck with 2048?

**Comment by Ph0rk0z** [comment]
You can set it to truncate at 4096 instead of 2048.

**Comment by St33lMouse** [comment]
No, what I mean is that if I do not limit context length in my front end, I'll error out. I don't see any way to permit 4096 context in ooba using auto gptq, and that's the only one that allows me to set no fused attention.

**Comment by sanixa** [comment]
I also have the same issue.

In my case, everything works fine for loading 70B models and attaching LORAs created by QLORA, but it fails during inference.

Afterward, I attempted the "monkey-patch" as described in https://github.com/oobabooga/text-generation-webui/blob/main/docs/GPTQ-models-(4-bit-mode).md but failed to compile https://github.com/sterlind/GPTQ-for-LLaMa.

Now, I have successfully trained LORAs when using the model loader "transformers" and the UI by ooba. However, there are still some issues, as described here: https://www.reddit.com/r/LocalLLaMA/comments/169g7il/if_you_train_qlora_in_transformers_peft_and_4bit/.

**Comment by Ph0rk0z** [comment]
need to add `config.fused_attn = False` to load lora in exllama.

Your other problem is because you use transformers loader with GPTQ. Don't use it this way because you will not get control of AutoGPTQ parameters.

If you want to train transformers you have to use bnb in int8/int4 or FP16 on the non quantized model.

**Comment by St33lMouse** [comment]
> need to add `config.fused_attn = False` to load lora in exllama.
> 
> Your other problem is because you use transformers loader with GPTQ. Don't use it this way because you will not get control of AutoGPTQ parameters.
> 
> If you want to train transformers you have to use bnb in int8/int4 or FP16 on the non quantized model.

In which file, exactly, would I add that config line?

**Comment by St33lMouse** [comment]
Never mind, figured it out. in case anyone is wondering:

One needs to switch to llama-HF model loader and uncomment the following line in modules/exllama_hf.py:

config.fused_attn = False

And your lora problems will go away!

**Comment by markrmiller** [comment]
This is a weird one because one day I'll hit and the next I won't and the next I will ...
