### ISSUE TITLE
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mushinbush** [oobabooga/text-generation-webui#4195]
### Brief Description of the Bug
I encountered an failure while attempting to boot up the webui server on a clean install of WSL using one-click installer.
I managed to resolve the problem by downgrading `triton` and successfully load the Exllama2 models.
It seems like there might be some issues related to dependency conflicts and version incompatibility when installing.

*Update 2 hours later: Pretty sure something was off, I reinstalled Windows and reinstalled the WSL WebUI, starting with a clean slate, but encountered the same issue. With `triton` version 2.1.0, the problem persisted. However, downgrading to 2.0.0 resolved the issue.
I initially clean installed the WSL WebUI on 09/29 without encountering any errors, so we can likely rule out any issues with my installation steps or hardware.
### Details
(Full log is in `Logs`)
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires triton==2.0.0, but you have triton 2.1.0 which is incompatible.
Traceback (most recent call last):
...
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```
The WebUI server terminated unexpectedly as the program couldn't continue and had to exit.

Resolution:
I was able to resolve the issue by downgrading the `triton` package to version 2.0.0 using `pip install triton==2.0.0`. By downgrading `triton`, is also seems to downgrade `torch` to 2.0.1, with following warnings.
```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchaudio 2.1.0 requires torch==2.1.0, but you have torch 2.0.1 which is incompatible.
torchvision 0.16.0 requires torch==2.1.0, but you have torch 2.0.1 which is incompatible.
```
This warning did not affect the webui server's functionality. The server successfully booted up and loaded the Exllama2 models without any issues.

Additional Note:
When opening `cmd_wsl.bat`, I also noticed a warning message:
```
bash: /home/mushinbush/text-gen-install/text-generation-webui/installer_files/env/lib/libtinfo.so.6: no version information available (required by bash)
```

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Clean install of wsl text-generation-webui, running `start_wsl.bat` and `A. NVIDIA` selected.

### Logs

```shell
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
openai-whisper 20230918 requires triton==2.0.0, but you have triton 2.1.0 which is incompatible.
Successfully installed DataProperty-1.0.1 GitPython-3.1.37 absl-py-2.0.0 accelerate-0.23.0 aiofiles-23.1.0 aiohttp-3.8.5 aiosignal-1.3.1 altair-5.1.2 anyio-4.0.0 appdirs-1.4.4 async-timeout-4.0.3 attributedict-0.3.0 attrs-23.1.0 auto-gptq-0.4.2+cu117 autoawq-0.1.3 bitsandbytes-0.41.1 blessings-1.7 cachetools-5.3.1 chardet-5.2.0 codecov-2.1.13 colorama-0.4.6 coloredlogs-15.0.1 colour-runner-0.1.1 contourpy-1.1.1 coverage-7.3.2 cramjam-2.7.0 ctransformers-0.2.27+cu117 cycler-0.12.0 datasets-2.14.5 deepdiff-6.6.0 dill-0.3.7 diskcache-5.6.3 distlib-0.3.7 docker-pycreds-0.4.0 einops-0.7.0 exllama-0.0.17+cu117 exllamav2-0.0.5+cu117 fastapi-0.95.2 fastparquet-2023.8.0 ffmpy-0.3.1 flash-attn-2.3.0 fonttools-4.43.0 frozenlist-1.4.0 fsspec-2023.6.0 gitdb-4.0.10 google-auth-2.23.2 google-auth-oauthlib-1.0.0 gptq-for-llama-0.1.0+cu117 gradio-3.33.1 gradio_client-0.2.5 grpcio-1.59.0 h11-0.14.0 httpcore-0.18.0 httpx-0.25.0 humanfriendly-10.0 inspecta-0.1.3 jsonlines-4.0.0 jsonschema-4.19.1 jsonschema-specifications-2023.7.1 kiwisolver-1.4.5 linkify-it-py-2.0.2 llama-cpp-python-0.2.11 llama-cpp-python-cuda-0.2.11+cu117 lm-eval-0.3.0 markdown-3.4.4 markdown-it-py-2.2.0 matplotlib-3.8.0 mbstrdecoder-1.1.3 mdit-py-plugins-0.3.3 mdurl-0.1.2 multidict-6.0.4 multiprocess-0.70.15 ninja-1.11.1 numexpr-2.8.7 numpy-1.24.0 oauthlib-3.2.2 openai-0.28.1 optimum-1.13.1 ordered-set-4.1.0 orjson-3.9.7 pandas-2.1.1 pathtools-0.1.2 pathvalidate-3.2.0 peft-0.5.0 platformdirs-3.11.0 pluggy-1.3.0 portalocker-2.8.2 protobuf-4.24.4 psutil-5.9.5 pyarrow-13.0.0 pyasn1-0.5.0 pyasn1-modules-0.3.0 pybind11-2.11.1 pycountry-22.3.5 pydantic-1.10.12 pyparsing-3.1.1 pyproject-api-1.6.1 pytablewriter-1.1.0 python-dateutil-2.8.2 python-multipart-0.0.6 pytz-2023.3.post1 referencing-0.30.2 requests-oauthlib-1.3.1 rootpath-0.1.1 rouge-1.0.1 rouge-score-0.1.2 rpds-py-0.10.4 rsa-4.9 sacrebleu-1.5.0 safetensors-0.3.2 semantic-version-2.10.0 sentry-sdk-1.31.0 setproctitle-1.3.3 smmap-5.0.1 sniffio-1.3.0 sqlitedict-2.1.0 starlette-0.27.0 tabledata-1.3.3 tabulate-0.9.0 tcolorpy-0.1.4 tensorboard-2.14.1 tensorboard-data-server-0.7.1 termcolor-2.3.0 texttable-1.7.0 toml-0.10.2 tomli-2.0.1 toolz-0.12.0 torch-2.1.0 torch-grammar-0.3.3 tox-4.11.3 tqdm-multiprocess-0.0.11 triton-2.1.0 typepy-1.3.2 tzdata-2023.3 uc-micro-py-1.0.2 uvicorn-0.23.2 virtualenv-20.24.5 wandb-0.15.12 xxhash-3.4.1 yarl-1.9.2 zstandard-0.21.0
Cloning into 'exllama'...
remote: Enumerating objects: 1523, done.
remote: Counting objects: 100% (851/851), done.
remote: Compressing objects: 100% (267/267), done.
remote: Total 1523 (delta 687), reused 618 (delta 583), pack-reused 672
Receiving objects: 100% (1523/1523), 942.05 KiB | 553.00 KiB/s, done.
Resolving deltas: 100% (1067/1067), done.
Will remove 76 (153.0 MB) tarball(s).
Will remove 1 index cache(s).
Will remove 4 (408 KB) package(s).
There are no tempfile(s) to remove.
There are no logfile(s) to remove.
Files removed: 649


*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File "/home/mushinbush/text-gen-install/text-generation-webui/server.py", line 30, in <module>
    from modules import (
  File "/home/mushinbush/text-gen-install/text-generation-webui/modules/chat.py", line 18, in <module>
    from modules.text_generation import (
  File "/home/mushinbush/text-gen-install/text-generation-webui/modules/text_generation.py", line 24, in <module>
    from modules.models import clear_torch_cache, local_rank
  File "/home/mushinbush/text-gen-install/text-generation-webui/modules/models.py", line 22, in <module>
    from modules import RoPE, llama_attn_hijack, sampler_hijack
  File "/home/mushinbush/text-gen-install/text-generation-webui/modules/llama_attn_hijack.py", line 7, in <module>
    import transformers.models.llama.modeling_llama
  File "/home/mushinbush/text-gen-install/text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File "/home/mushinbush/text-gen-install/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File "/home/mushinbush/text-gen-install/text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

### System Info

```shell
Windows 10, WSL 2.0.4.0, Ubuntu 22.04 LTS, RTX 3090
```

**Comment by yhyu13** [comment]
@mushinbush 

Did you sudo apt install cuda-12.2 or whatever cuda version you want to install?

It is likely that you have not installed CUDA toolkit correctly. The Conda packaged cuda tool kit misses some essential .so files that you can only find from a proper apt install

**Comment by exepirit** [comment]
I have same issue on fresh `text-generation-webui`. It is not CUDA installation issue, cause other CUDA application working correctly, e. g. Stable Diffusion WebUI.

```shell
$ git rev-parse HEAD                                                                                                                                              
7d3201923bae5a070b107794bd364bb3478b7788

$ /usr/local/cuda/bin/nvcc --version                                                                                                                              
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Tue_Feb__7_19:32:13_PST_2023
Cuda compilation tools, release 12.1, V12.1.66
Build cuda_12.1.r12.1/compiler.32415258_0

$ ls /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so*                                                                                                       
/usr/local/cuda/targets/x86_64-linux/lib/libcudart.so  /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12  /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12.1.55

$ ./start_linux.sh

*******************************************************************
* WARNING: You haven't downloaded any model yet.
* Once the web UI launches, head over to the "Model" tab and download one.
*******************************************************************


Traceback (most recent call last):
  File ".../text-generation-webui/server.py", line 30, in <module>
    from modules import (
  File ".../text-generation-webui/modules/chat.py", line 18, in <module>
    from modules.text_generation import (
  File ".../text-generation-webui/modules/text_generation.py", line 24, in <module>
    from modules.models import clear_torch_cache, local_rank
  File ".../text-generation-webui/modules/models.py", line 22, in <module>
    from modules import RoPE, llama_attn_hijack, sampler_hijack
  File ".../text-generation-webui/modules/llama_attn_hijack.py", line 7, in <module>
    import transformers.models.llama.modeling_llama
  File ".../text-generation-webui/installer_files/env/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 45, in <module>
    from flash_attn import flash_attn_func, flash_attn_varlen_func
  File ".../text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/__init__.py", line 3, in <module>
    from flash_attn.flash_attn_interface import (
  File ".../text-generation-webui/installer_files/env/lib/python3.10/site-packages/flash_attn/flash_attn_interface.py", line 8, in <module>
    import flash_attn_2_cuda as flash_attn_cuda
ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory
```

**Comment by MrEdwards007** [comment]
I'm a first time user\installer and I just had the same issue on Linux Ubuntu 22.0, using CUDA 12.2

I dont understand but after I finished the install, there was an additional environment in the install directory that included triton 2.1.  Once I found this issue posted, I used Anaconda to activate the path to the installation directory, which shows up in Anaconda as "env".  I performed a pip install triton==2.0 and the oobabooga program executed.

**Comment by bdashore3** [comment]
The reason why downgrading to triton 2.0.0 works is because the downgrade also installs the cuda 11 runtime and toolkit that pytorch usually downloads. However, doing this also downgrades your pytorch version to 2.0.1.

Here's an easier fix for this issue (I'd recommend doing a clean install first):
1. Run `cmd_wsl.bat` or `cmd_linux.sh`
2. Run `conda install -y -c "nvidia/label/cuda-11.8.0" cuda-toolkit cuda-runtime`

This installs the cuda toolkit and runtime (v11.8) in the conda environment, which is compatible with all the dependencies from my testing since ooba launched, loaded models, and generated fine afterwards. Torch is 2.1 and all the latest packages are now being used.

**Comment by mushinbush** [comment]
@bdashore3
I appreciate your response! I won't be testing it as it's currently functioning well for me.
If it turns out to be the issue, I suggest the command in docs/One-Click-Installers.md
```
conda install cuda -c nvidia/label/cuda-11.7.1
```
can be deemed as "essential."

**Comment by bdashore3** [comment]
That should be updated along with the oneclick installer to use `conda install -y -c "nvidia/label/cuda-11.8.0" cuda-toolkit cuda-runtime` (what I pasted above)

**Comment by ottokafka** [comment]
I had the same issue `ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory`

None of the above work for me. Here's what I did to solve the issue.

Step 1. Cleaned out package from site-packages directory 
```
cd .local/lib/python3.10/site-packages
ls | xargs rm -r
```

Step 2. reinstall packages with `pip install -r requirements.txt`

**Comment by Oninaig** [comment]
> The reason why downgrading to triton 2.0.0 works is because the downgrade also installs the cuda 11 runtime and toolkit that pytorch usually downloads. However, doing this also downgrades your pytorch version to 2.0.1.
> 
> Here's an easier fix for this issue (I'd recommend doing a clean install first):
> 
> 1. Run `cmd_wsl.bat` or `cmd_linux.sh`
> 2. Run `conda install -y -c "nvidia/label/cuda-11.8.0" cuda-toolkit cuda-runtime`
> 
> This installs the cuda toolkit and runtime (v11.8) in the conda environment, which is compatible with all the dependencies from my testing since ooba launched, loaded models, and generated fine afterwards. Torch is 2.1 and all the latest packages are now being used.

Tried this on an ubuntu server that was working yesterday with a 3090. Today I ran `update_linux` and started getting the same error: `ImportError: libcudart.so.12: cannot open shared object file: No such file or directory`

I tried 

```
conda install -y -c "nvidia/label/cuda-11.8.0" cuda-toolkit cuda-runtime
```

and 
`conda install cuda -c nvidia/label/cuda-11.7.1`

Neither resolved the issue. I am going to keep digging.

**Comment by mushinbush** [comment]
@Oninaig 
I'm not sure about the Linux situation, but in Windows, my understanding is that the text-generation-webui is using CUDA from a Conda environment, which is different from the CUDA installed in the system. Also, since it's using Miniconda but not the Conda you installed in your system, are you using the following commands in `cmd_linux.sh`?
```
conda install -y -c "nvidia/label/cuda-11.8.0" cuda-toolkit cuda-runtime
```
After running this command, you can try running `update_linux.sh` again to see if it works.

**Comment by Oninaig** [comment]
> @Oninaig I'm not sure about the Linux situation, but in Windows, my understanding is that the text-generation-webui is using CUDA from a Conda environment, which is different from the CUDA installed in the system. Also, since it's using Miniconda but not the Conda you installed in your system, are you using the following commands in `cmd_linux.sh`?
> 
> ```
> conda install -y -c "nvidia/label/cuda-11.8.0" cuda-toolkit cuda-runtime
> ```
> 
> After running this command, you can try running `update_linux.sh` again to see if it works.

Yeah turns out it was user error, I had cuda version 12 floating around that it kept trying to use, after forcefully removing that and making sure I installed 11.7 within the venv, everything works.

**Comment by aarongerber** [comment]
Nothing above has seemed to work for me. Guess I'll never know how AWQ works on PopOS... sniff, sniff.

**Comment by HariNuve** [comment]
libcudart.so.11.0: cannot open shared object file: No such file or directory

I have the same issue.
