### ISSUE TITLE
Missing files after fresh installation on linux, the program does not start.

### ISSUE THREAD

**Issue by gitologismus** [oobabooga/text-generation-webui#4236]
### Describe the bug

The start_linux.sh produces the error message:

"CUDA Setup failed despite GPU being available. Please run the following command to get more information:"

and complains about missing files: 'libcudart.so.11.0', 'libcudart.so.12.0'

The files are not on my pc. "find / -name libcudart.so.11.0 2>/dev/null" returns nothing.

See log for more details.

My system is on CUDA 12.2 and LD_LIBRARY_PATH points to /usr/local/cuda/lib64. In this directory, there is only libcudart.so, libcudart.so.12, libcudart.so.12.2.140.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. delete old install, then proceed with: git clone https://github.com/oobabooga/text-generation-webui
2. execute start_linux.sh
3. Observe the error mentioned above
4. Follow this procedure: "For one-click installer users: If you encounter problems after updating, rerun the update script. If issues persist, delete the installer_files folder and use the start script to reinstall requirements."
5. Still seeing the error

### Logs

```shell
False

/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /home/user/text-generation-webui/installer_files/env did not contain ['[libcudart.so](https://libcudart.so/)', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...

warn(msg)

/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cuda_setup/main.py:166: UserWarning: /usr/local/cuda/lib64: did not contain ['[libcudart.so](https://libcudart.so/)', 'libcudart.so.11.0', 'libcudart.so.12.0'] as expected! Searching further paths...

warn(msg)

The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Seat0')}

The following directories listed in your path were found to be non-existent: {PosixPath('local/user'), PosixPath('@/tmp/.ICE-unix/1590,unix/user')}

The following directories listed in your path were found to be non-existent: {PosixPath('/org/freedesktop/DisplayManager/Session0')}

The following directories listed in your path were found to be non-existent: {PosixPath('/org/gnome/Terminal/screen/3f6a2854_dba9_4b35_b53a_5587e37cfd44')}

The following directories listed in your path were found to be non-existent: {PosixPath('/home/user/.cache/dotnet_bundle_extract')}

The following directories listed in your path were found to be non-existent: {PosixPath('0'), PosixPath('1')}

The following directories listed in your path were found to be non-existent: {PosixPath('/etc/xdg/xdg-cinnamon')}

CUDA_SETUP: WARNING! [libcudart.so](https://libcudart.so/) not found in any environmental path. Searching in backup paths...

DEBUG: Possible options found for [libcudart.so](https://libcudart.so/): {PosixPath('/usr/local/cuda/lib64/libcudart.so')}

CUDA SETUP: PyTorch settings found: CUDA_VERSION=118, Highest Compute Capability: 8.9.

CUDA SETUP: To manually override the PyTorch CUDA version please see:https://github.com/TimDettmers/bitsandbytes/blob/main/how_to_use_nonpytorch_cuda.md

CUDA SETUP: Loading binary /home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda118.so...

libcusparse.so.11: cannot open shared object file: No such file or directory

CUDA SETUP: Something unexpected happened. Please compile from source:

git clone https://github.com/TimDettmers/bitsandbytes.git

cd bitsandbytes

CUDA_VERSION=118 make cuda11x

python [setup.py](https://setup.py/) install

Traceback (most recent call last):

File "/home/user/text-generation-webui/server.py", line 30, in <module>

from modules import (

File "/home/user/text-generation-webui/modules/training.py", line 21, in <module>

from peft import (

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/__init__.py", line 22, in <module>

from .auto import (

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/auto.py", line 31, in <module>

from .mapping import MODEL_TYPE_TO_PEFT_MODEL_MAPPING

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/mapping.py", line 23, in <module>

from .peft_model import (

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/peft_model.py", line 38, in <module>

from .tuners import (

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/tuners/__init__.py", line 21, in <module>

from .lora import LoraConfig, LoraModel

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/peft/tuners/lora.py", line 45, in <module>

import bitsandbytes as bnb

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/__init__.py", line 6, in <module>

from . import cuda_setup, utils, research

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/__init__.py", line 1, in <module>

from . import nn

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/__init__.py", line 1, in <module>

from .modules import LinearFP8Mixed, LinearFP8Global

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/research/nn/modules.py", line 8, in <module>

from bitsandbytes.optim import GlobalOptimManager

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/optim/__init__.py", line 6, in <module>

from bitsandbytes.cextension import COMPILED_WITH_CUDA

File "/home/user/text-generation-webui/installer_files/env/lib/python3.10/site-packages/bitsandbytes/cextension.py", line 20, in <module>

raise RuntimeError('''

RuntimeError:

CUDA Setup failed despite GPU being available. Please run the following command to get more information:


python -m bitsandbytes


Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them

to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes

and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
```

### System Info

```shell
Linux Mint, 4090, using the install script.
```

**Comment by imakesound** [comment]
Same exact issue on manjaro linux with a 4090, i have tried reinstalling multiple times, deleting the installer files and running the update script repeatedly as well but the issue persists.

**Comment by gitologismus** [comment]
I tried removing the system wide CUDA installation in case something in it interferes somehow, then redid all the steps above, but that also did not work.

**Comment by MagnusMagnuson** [comment]
Had the same issue on WSL. This fixed it for me.

https://github.com/oobabooga/text-generation-webui/issues/4195#issuecomment-1751747331

**Comment by imakesound** [comment]
> I had the same issue on WSL. This fixed it for me.
> 
> [#4195 (comment)](https://github.com/oobabooga/text-generation-webui/issues/4195#issuecomment-1751747331)

This worked for me, thank you!

**Comment by oobabooga** [comment]
I have reproduced this issue and posted my solution here: https://github.com/oobabooga/text-generation-webui/issues/4260

It is similar to the one above but will download less files.

**Comment by gitologismus** [comment]
Just FIY, a completely fresh linux mint 21.2 installation works fine. No workaround needed.
