### ISSUE TITLE
CUDA error " Error 804: forward compatibility was attempted on non supported HW" when trying to launch docker image.

### ISSUE THREAD

**Issue by Blabter** [oobabooga/text-generation-webui#4407]
### Describe the bug

When I'm trying to build and launch Docker image:
```sh
git clone https://github.com/oobabooga/text-generation-webui.git
cd text-generation-webui
ln -s docker/{Dockerfile,docker-compose.yml,.dockerignore} .
cp docker/.env.example .env
# Edit .env and set TORCH_CUDA_ARCH_LIST based on your GPU model
docker compose up --build
```
I get CUDA error:
```
text-generation-webui_1  | /app/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
text-generation-webui_1  |   return torch._C._cuda_getDeviceCount() > 0
text-generation-webui_1  | 2023-10-27 20:32:19 INFO:Loading llama-2-7b.Q4_K_M.gguf...
text-generation-webui_1  | 2023-10-27 20:32:19 INFO:llama.cpp weights detected: models/llama-2-7b.Q4_K_M.gguf
text-generation-webui_1  | 2023-10-27 20:32:19 INFO:Cache capacity is 0 bytes
text-generation-webui_1  | 
text-generation-webui_1  | CUDA error 804 at /home/runner/work/llama-cpp-python-cuBLAS-wheels/llama-cpp-python-cuBLAS-wheels/vendor/llama.cpp/ggml-cuda.cu:5572: forward compatibility was attempted on non supported HW
text-generation-webui_1  | current device: 21876
text-generation-webui_1  | /arrow/cpp/src/arrow/filesystem/s3fs.cc:2829:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
text-generation-webui_text-generation-webui_1 exited with code 1
```
Here is output of `nvidia-smi`:
```
Fri Oct 27 23:40:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
| 45%   31C    P8    N/A /  75W |    448MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      1636      G   /usr/lib/xorg/Xorg                135MiB |
|    0   N/A  N/A      1973      G   /usr/bin/plasmashell               36MiB |
|    0   N/A  N/A      5253      G   ...RendererForSitePerProcess       27MiB |
|    0   N/A  N/A     13353      G   /usr/lib/firefox/firefox          241MiB |
|    0   N/A  N/A     32596      G   .../usr/bin/telegram-desktop        1MiB |
+-----------------------------------------------------------------------------+
```

I tried next `TORCH_CUDA_ARCH_LIST` options in `.env` file:
```env
TORCH_CUDA_ARCH_LIST=7.5
TORCH_CUDA_ARCH_LIST=-3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX #It's default value
TORCH_CUDA_ARCH_LIST=6.1 #It's from https://developer.nvidia.com/cuda-gpus for my GPU
TORCH_CUDA_ARCH_LIST=12.1
```

Everything gives same error.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```sh
git clone https://github.com/oobabooga/text-generation-webui.git
cd text-generation-webui
ln -s docker/{Dockerfile,docker-compose.yml,.dockerignore} .
cp docker/.env.example .env
# Edit .env and set TORCH_CUDA_ARCH_LIST based on your GPU model
docker compose up --build
```

### Logs

```shell
text-generation-webui_1  | /app/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
text-generation-webui_1  |   return torch._C._cuda_getDeviceCount() > 0
text-generation-webui_1  | 2023-10-27 20:32:19 INFO:Loading llama-2-7b.Q4_K_M.gguf...
text-generation-webui_1  | 2023-10-27 20:32:19 INFO:llama.cpp weights detected: models/llama-2-7b.Q4_K_M.gguf
text-generation-webui_1  | 2023-10-27 20:32:19 INFO:Cache capacity is 0 bytes
text-generation-webui_1  | 
text-generation-webui_1  | CUDA error 804 at /home/runner/work/llama-cpp-python-cuBLAS-wheels/llama-cpp-python-cuBLAS-wheels/vendor/llama.cpp/ggml-cuda.cu:5572: forward compatibility was attempted on non supported HW
text-generation-webui_1  | current device: 21876
text-generation-webui_1  | /arrow/cpp/src/arrow/filesystem/s3fs.cc:2829:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
text-generation-webui_text-generation-webui_1 exited with code 1
```
```
### System Info

Ubuntu 20.04.6 LTS
GTX 1050 Ti
```

**Comment by FoRVaiS** [comment]
I'm also getting an error 804 but I'm not entirely sure if the problem is the same?

Using the docker image from commit 515bc13...

## Logs

### text-generation-webui
```shell
text-generation-webui-1  |
text-generation-webui-1  | ==========
text-generation-webui-1  | == CUDA ==
text-generation-webui-1  | ==========
text-generation-webui-1  |
text-generation-webui-1  | CUDA Version 12.1.0
text-generation-webui-1  |
text-generation-webui-1  | Container image Copyright (c) 2016-2023, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
text-generation-webui-1  |
text-generation-webui-1  | This container image and its contents are governed by the NVIDIA Deep Learning Container License.
text-generation-webui-1  | By pulling and using the container, you accept the terms and conditions of this license:
text-generation-webui-1  | https://developer.nvidia.com/ngc/nvidia-deep-learning-container-license
text-generation-webui-1  |
text-generation-webui-1  | A copy of this license is made available in this container at /NGC-DL-CONTAINER-LICENSE for your convenience.
text-generation-webui-1  |
text-generation-webui-1  | *************************
text-generation-webui-1  | ** DEPRECATION NOTICE! **
text-generation-webui-1  | *************************
text-generation-webui-1  | THIS IMAGE IS DEPRECATED and is scheduled for DELETION.
text-generation-webui-1  |     https://gitlab.com/nvidia/container-images/cuda/blob/master/doc/support-policy.md
text-generation-webui-1  |
text-generation-webui-1  | 2023-10-28 05:50:29 WARNING:
text-generation-webui-1  | You are potentially exposing the web UI to the entire internet without any access password.
text-generation-webui-1  | You can create one with the "--gradio-auth" flag like this:
text-generation-webui-1  |
text-generation-webui-1  | --gradio-auth username:password
text-generation-webui-1  |
text-generation-webui-1  | Make sure to replace username:password with your own.
text-generation-webui-1  | /app/venv/lib/python3.10/site-packages/torch/cuda/__init__.py:138: UserWarning: CUDA initialization: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
text-generation-webui-1  |   return torch._C._cuda_getDeviceCount() > 0
text-generation-webui-1  | 2023-10-28 05:50:31 INFO:Loading the extension "gallery"...
text-generation-webui-1  | Traceback (most recent call last):
text-generation-webui-1  |   File "/app/server.py", line 230, in <module>
text-generation-webui-1  |     create_interface()
text-generation-webui-1  |   File "/app/server.py", line 117, in create_interface
text-generation-webui-1  |     ui_model_menu.create_ui()  # Model tab
text-generation-webui-1  |   File "/app/modules/ui_model_menu.py", line 31, in create_ui
text-generation-webui-1  |     total_mem.append(math.floor(torch.cuda.get_device_properties(i).total_memory / (1024 * 1024)))
text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 449, in get_device_properties
text-generation-webui-1  |     _lazy_init()  # will define _get_device_properties
text-generation-webui-1  |   File "/app/venv/lib/python3.10/site-packages/torch/cuda/__init__.py", line 298, in _lazy_init
text-generation-webui-1  |     torch._C._cuda_init()
text-generation-webui-1  | RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
text-generation-webui-1 exited with code 1

```
### nvidia-smi
```shell
-> % nvidia-smi
Fri Oct 27 22:53:49 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.125.06   Driver Version: 525.125.06   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:0B:00.0  On |                  N/A |
|  0%   42C    P3    55W / 340W |    530MiB / 16376MiB |     11%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A      2862      G   /usr/lib/xorg/Xorg                182MiB |
|    0   N/A  N/A      3198      G   /usr/bin/gnome-shell               58MiB |
|    0   N/A  N/A      7172      G   ...0/usr/lib/firefox/firefox      286MiB |
+-----------------------------------------------------------------------------+
```
## Config
### .env
```.env
# by default the Dockerfile specifies these versions: 3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX
# however for me to work i had to specify the exact version for my card ( 2060 ) it was 7.5
# https://developer.nvidia.com/cuda-gpus you can find the version for your card here
TORCH_CUDA_ARCH_LIST=8.9

# these commands worked for me with roughly 4.5GB of vram
CLI_ARGS=--listen --auto-devices

# the following examples have been tested with the files linked in docs/README_docker.md:
# example running 13b with 4bit/128 groupsize        : CLI_ARGS=--model llama-13b-4bit-128g --wbits 4 --listen --groupsize 128 --pre_layer 25
# example with loading api extension and public share: CLI_ARGS=--model llama-7b-4bit --wbits 4 --listen --auto-devices --no-stream --extensions api --share
# example running 7b with 8bit groupsize             : CLI_ARGS=--model llama-7b --load-in-8bit --listen --auto-devices

# the port the webui binds to on the host
HOST_PORT=7860
# the port the webui binds to inside the container
CONTAINER_PORT=7860

# the port the api binds to on the host
HOST_API_PORT=5000
# the port the api binds to inside the container
CONTAINER_API_PORT=5000

# the port the api stream endpoint binds to on the host
HOST_API_STREAM_PORT=5005
# the port the api stream endpoint binds to inside the container
CONTAINER_API_STREAM_PORT=5005

# the version used to install text-generation-webui from
WEBUI_VERSION=HEAD
```

## System
**OS**: Ubuntu 22.04
**GPU**: NV 4080
**Docker**: 24.0.7, build afdd53b
**Docker-Compose**: v2.21.0

**Comment by nalf3in** [comment]
This is caused by the fact that your version of the nvidia driver doesn't support the new cuda version used by text-generation-webui  (12.1). Of course you can update the drivers and that will fix it but otherwise you need to use an old version of the compose file that uses a version supported by your hardware. 

In this case you can just git clone the latest version and manually edit the Dockerfile by using this version: https://github.com/oobabooga/text-generation-webui/blob/d331501ebc83e80c5d8f49c3e7c547730afff5c2/docker/Dockerfile

@oobabooga I think supporting 11.8 or at least mentioning this issue in the readme would be nice. Would you like a pr ?

**Comment by Blabter** [comment]
> This is caused by the fact that your version of the nvidia driver doesn't support the new cuda version used by text-generation-webui (12.1). Of course you can update the drivers and that will fix it but otherwise you need to use an old version of the compose file that uses a version supported by your hardware.
> 
> In this case you can just git clone the latest version and manually edit the Dockerfile by using this version: https://github.com/oobabooga/text-generation-webui/blob/d331501ebc83e80c5d8f49c3e7c547730afff5c2/docker/Dockerfile
> 
> If you prefer the command line version of it `git clone https://github.com/oobabooga/text-generation-webui.git` `cd text-generation-webui` `git checkout d331501ebc83e80c5d8f49c3e7c547730afff5c2 -- docker/Dockerfile` `docker compose build ...`
> 
> @oobabooga I think supporting 11.8 or at least mentioning this issue in the readme would be nice. Would you like a pr ?

Hi. Thanks for your answer. I'm updated NVIDIA drivers from 525.125.06 to 535.113.01, so now my `nivia-smi` looks like this:
```
Mon Oct 30 01:52:16 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.113.01             Driver Version: 535.113.01   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1050 Ti     Off | 00000000:01:00.0  On |                  N/A |
| 45%   29C    P0              N/A /  75W |    354MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
                                                                                         
+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1631      G   /usr/lib/xorg/Xorg                          135MiB |
|    0   N/A  N/A      1948      G   /usr/bin/plasmashell                         38MiB |
|    0   N/A  N/A      4778      G   /usr/lib/firefox/firefox                    174MiB |
|    0   N/A  N/A      5339      G   ...ures=SpareRendererForSitePerProcess        1MiB |
+---------------------------------------------------------------------------------------+
```
But now during build I get error:
```
 > [builder 6/6] RUN . /build/venv/bin/activate &&     python3 setup_cuda.py bdist_wheel -d .:
1.798 No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
1.822 running bdist_wheel
1.863 running build
1.863 running build_ext
1.868 /build/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py:424: UserWarning: There are no x86_64-linux-gnu-g++ version bounds defined for CUDA version 12.1
1.868   warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
1.868 building 'quant_cuda' extension
1.868 creating /build/build
1.869 creating /build/build/temp.linux-x86_64-cpython-310
1.869 Traceback (most recent call last):
1.869   File "/build/setup_cuda.py", line 4, in <module>
1.869     setup(
1.869   File "/build/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
1.869     return distutils.core.setup(**attrs)
1.869   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
1.869     return run_commands(dist)
1.869   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
1.869     dist.run_commands()
1.869   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
1.869     self.run_command(cmd)
1.869   File "/build/venv/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
1.869     super().run_command(command)
1.869   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
1.870     cmd_obj.run()
1.870   File "/build/venv/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 364, in run
1.870     self.run_command("build")
1.870   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
1.870     self.distribution.run_command(command)
1.870   File "/build/venv/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
1.870     super().run_command(command)
1.870   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
1.870     cmd_obj.run()
1.870   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 131, in run
1.870     self.run_command(cmd_name)
1.870   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
1.870     self.distribution.run_command(command)
1.870   File "/build/venv/lib/python3.10/site-packages/setuptools/dist.py", line 989, in run_command
1.870     super().run_command(command)
1.870   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
1.871     cmd_obj.run()
1.871   File "/build/venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 88, in run
1.871     _build_ext.run(self)
1.871   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
1.871     self.build_extensions()
1.871   File "/build/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 873, in build_extensions
1.871     build_ext.build_extensions(self)
1.871   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
1.871     self._build_extensions_serial()
1.871   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
1.871     self.build_extension(ext)
1.871   File "/build/venv/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 249, in build_extension
1.871     _build_ext.build_extension(self, ext)
1.871   File "/build/venv/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 548, in build_extension
1.871     objects = self.compiler.compile(
1.871   File "/build/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 677, in unix_wrap_ninja_compile
1.871     cuda_post_cflags = unix_cuda_flags(cuda_post_cflags)
1.871   File "/build/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 576, in unix_cuda_flags
1.871     cflags + _get_cuda_arch_flags(cflags))
1.871   File "/build/venv/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1993, in _get_cuda_arch_flags
1.872     raise ValueError(f"Unknown CUDA arch ({arch}) or GPU not supported")
1.872 ValueError: Unknown CUDA arch (12.1) or GPU not supported
------
Dockerfile:21
--------------------
  20 |     ARG TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST:-3.5;5.0;6.0;6.1;7.0;7.5;8.0;8.6+PTX}"
  21 | >>> RUN . /build/venv/bin/activate && \
  22 | >>>     python3 setup_cuda.py bdist_wheel -d .
  23 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c . /build/venv/bin/activate &&     python3 setup_cuda.py bdist_wheel -d ." did not complete successfully: exit code: 1
ERROR: Service 'text-generation-webui' failed to build : Build failed
```
I'm not sure if it's related to my original problem or not.
