### ISSUE TITLE
mismatched cuda error

### ISSUE THREAD

**Issue by gsgoldma** [oobabooga/text-generation-webui#457]
### Describe the bug

i've looked at the troubleshooting posts, but perhaps i've missed something.

trying this on windows 10 for 4bit precision with 7b model

I got the regular webui running with pyg model just fine but I keep running into errors with this, different ones each time/
here's the latest error trying to use python setup_cuda.py

d:\myenvs\textgen1\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
traceback---------------------

RuntimeError:
The detected CUDA version (12.0) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

normal installation, use visual studio 2019 with desktop, pip install main webui/gptq, use the conda forge command, and then try the cuda_setup.py

### Logs

```shell
(d:\myenvs\textgen1) D:\text-generation-webui\repositories\GPTQ-for-LLaMa>python setup_cuda.py install
running install
d:\myenvs\textgen1\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
d:\myenvs\textgen1\lib\site-packages\setuptools\command\easy_install.py:144: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
running bdist_egg
running egg_info
writing quant_cuda.egg-info\PKG-INFO
writing dependency_links to quant_cuda.egg-info\dependency_links.txt
writing top-level names to quant_cuda.egg-info\top_level.txt
reading manifest file 'quant_cuda.egg-info\SOURCES.txt'
writing manifest file 'quant_cuda.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_ext
d:\myenvs\textgen1\lib\site-packages\torch\utils\cpp_extension.py:359: UserWarning: Error checking compiler version for cl: [WinError 2] The system cannot find the file specified
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):
  File "D:\text-generation-webui\repositories\GPTQ-for-LLaMa\setup_cuda.py", line 4, in <module>
    setup(
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\__init__.py", line 87, in setup
    return distutils.core.setup(**attrs)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\command\install.py", line 74, in run
    self.do_egg_install()
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\command\install.py", line 123, in do_egg_install
    self.run_command('bdist_egg')
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\command\bdist_egg.py", line 165, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\command\bdist_egg.py", line 151, in call_command
    self.run_command(cmdname)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\command\install_lib.py", line 11, in run
    self.build()
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\command\install_lib.py", line 112, in build
    self.run_command('build_ext')
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\dist.py", line 1208, in run_command
    super().run_command(command)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\command\build_ext.py", line 84, in run
    _build_ext.run(self)
  File "d:\myenvs\textgen1\lib\site-packages\setuptools\_distutils\command\build_ext.py", line 346, in run
    self.build_extensions()
  File "d:\myenvs\textgen1\lib\site-packages\torch\utils\cpp_extension.py", line 499, in build_extensions
    _check_cuda_version(compiler_name, compiler_version)
  File "d:\myenvs\textgen1\lib\site-packages\torch\utils\cpp_extension.py", line 387, in _check_cuda_version
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError:
The detected CUDA version (12.0) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.
```

### System Info

```shell
windows 10, nvidia 980 6gigs, local install
```

**Comment by jllllll** [comment]
Default install instructions for pytorch will install 12.0 cuda files. The easiest way that I've found to get around this is to install pytorch using conda:
```
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit -c "nvidia/label/cuda-11.7.0" -c pytorch -c nvidia
```
This command includes the official cuda-toolkit install which makes the conda-forge command redundant. If you would prefer to use conda-forge, then you can remove `cuda-toolkit` from the above command.

**Comment by gsgoldma** [comment]
shouldnt that be changed if its causing this error?

**Comment by jllllll** [comment]
Make sure that you are on the `468c47c01b4fe370616747b6d69a2d3f48bab5e4` revision of gptq-for-llama. Run this command in the gptq-for-llama folder:
`git reset --hard 468c47c01b4fe370616747b6d69a2d3f48bab5e4`
I just successfully compiled gptq-for-llama in Windows using VS 2022 after using that `cuda-toolkit -c "nvidia/label/cuda-11.7.0"` command, so I know it works.

**Comment by jllllll** [comment]
Conda will not re-install already existing packages, even if they are a different version. You can use `--force-reinstall`, but in my experience, you are better off just re-creating the environment. Also, I am using the latest version of conda, though I'm not sure that would make any difference.

**Comment by gsgoldma** [comment]
are there any steps to avoid that you did differently?

**Comment by jllllll** [comment]
This is the entirety of my install batch script:
```
@echo off

call D:\Programs\miniconda3\Scripts\activate.bat D:\Programs\miniconda3 || goto end &REM This is to prime conda for use. Will need different paths for your install.

call conda create -p %cd%\textgen pytorch torchvision torchaudio pytorch-cuda=11.7 cuda-toolkit -c "nvidia/label/cuda-11.7.0" -c pytorch -c nvidia
call conda activate %cd%\textgen

git clone https://github.com/oobabooga/text-generation-webui
cd text-generation-webui || goto end
pip install -r requirements.txt

mkdir repositories
cd repositories || goto end
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa
cd GPTQ-for-LLaMa
git reset --hard 468c47c01b4fe370616747b6d69a2d3f48bab5e4
pip install -r requirements.txt

pip install ninja
call python setup_cuda.py install

:end
pause
```

**Comment by jllllll** [comment]
Here is a pre-compiled wheel made using the environment created from the script above:
[quant_cuda-0.0.0-cp310-cp310-win_amd64.whl.zip](https://github.com/oobabooga/text-generation-webui/files/11023775/quant_cuda-0.0.0-cp310-cp310-win_amd64.whl.zip)
It can be installed with: `pip install quant_cuda-0.0.0-cp310-cp310-win_amd64.whl`
This should work if you can't get yours to compile. If any significant updates occur, or your conda environment is significantly different to mine, then this wheel will produce bad model output.

**Comment by gsgoldma** [comment]
got a ton of errors trying that, damn

**Comment by jllllll** [comment]
> got a ton of errors trying that, damn

The batch script? Make sure to change the paths on that first call line to match your miniconda install.

**Comment by jllllll** [comment]
That's pretty weird. It's using the x64 compiler, but it can't find quant_cuda.cpp. You should just install the wheel that I uploaded above. No clue what's going on with that.

**Comment by gsgoldma** [comment]
im definitely running as admin, thats what the instructions said with powershell and chatgpt told me to as well when permissions got weird.

im probably going to nuke it all and try again

and to think I get stable diffuison up and running in no time

**Comment by jllllll** [comment]
The issue with running as admin is that it will change your current directory to your user directory before executing the script. I was able to successfully run the script without running as admin. Just put the script where you want to install the webui and double-click it.

**Comment by gsgoldma** [comment]
"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\nvcc" -c quant_cuda_kernel.cu -o build\temp.win-amd64-cpython-310\Release\quant_cuda_kernel.obj -ID:\textgen1\lib\site-packages\torch\include -ID:\textgen1\lib\site-packages\torch\include\torch\csrc\api\include -ID:\textgen1\lib\site-packages\torch\include\TH -ID:\textgen1\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include" -ID:\textgen1\include -ID:\textgen1\Include "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.34.31933\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\VS\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.22000.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\um" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\shared" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\winrt" "-IC:\Program Files (x86)\Windows Kits\10\\include\10.0.22000.0\\cppwinrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um" -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=quant_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_52,code=compute_52 -gencode=arch=compute_52,code=sm_52 --use-local-env
quant_cuda_kernel.cu
D:/textgen1/lib/site-packages/torch/include\c10/macros/Macros.h(138): warning C4067: unexpected tokens following preprocessor directive - expected a newline
D:/textgen1/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
(61): here
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=false, <unnamed>=0]"
D:/textgen1/lib/site-packages/torch/include\c10/core/TensorImpl.h(77): here

D:/textgen1/lib/site-packages/torch/include\c10/util/irange.h(54): warning #186-D: pointless comparison of unsigned integer with zero
          detected during:
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator==(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
(61): here
            instantiation of "__nv_bool c10::detail::integer_iterator<I, one_sided, <unnamed>>::operator!=(const c10::detail::integer_iterator<I, one_sided, <unnamed>> &) const [with I=size_t, one_sided=true, <unnamed>=0]"
D:/textgen1/lib/site-packages/torch/include\ATen/core/qualified_name.h(73): here

quant_cuda_kernel.cu(149): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant2MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]"
(87): here

quant_cuda_kernel.cu(261): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant3MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]"
(171): here

quant_cuda_kernel.cu(337): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant4MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]"
(283): here

quant_cuda_kernel.cu(409): error: no instance of overloaded function "atomicAdd" matches the argument list
            argument types are: (double *, double)
          detected during instantiation of "void VecQuant8MatMulKernel(const scalar_t *, const int *, scalar_t *, const scalar_t *, const scalar_t *, int, int, int, int) [with scalar_t=double]"
(359): here

4 errors detected in the compilation of "quant_cuda_kernel.cu".
error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.7\\bin\\nvcc.exe' failed with exit code 1
Press any key to continue . . .

a seemingly infinitely long error before that part of it

**Comment by jllllll** [comment]
Like I said, you are better off installing the wheel file that I uploaded: https://github.com/oobabooga/text-generation-webui/issues/457#issuecomment-1477075495
TBH, I don't really know why compilation started working for me. At first, I was getting constant errors like you. Then my computer restarted overnight and in the morning it just started working. Maybe the restart did it? No clue, because I had tried it before. Just place that wheel file in the gptq folder and install it within the conda environment.

**Comment by gsgoldma** [comment]
that file causes all sorts of problems. trying WSL now and just FLOODED with errors at every turn

**Comment by jllllll** [comment]
The wheel is for Windows, not WSL. It will allow you to skip the GPTQ-for-LLaMa compilation that wasn't working.

**Comment by xNul** [comment]
> Like I said, you are better off installing the wheel file that I uploaded: [#457 (comment)](https://github.com/oobabooga/text-generation-webui/issues/457#issuecomment-1477075495) TBH, I don't really know why compilation started working for me. At first, I was getting constant errors like you. Then my computer restarted overnight and in the morning it just started working. Maybe the restart did it? No clue, because I had tried it before. Just place that wheel file in the gptq folder and install it within the conda environment.

Similar case to me as well. I installed VS BuildTools but the `setup_cuda.py` file couldn't find the compiler and if it did, it would give me some access denied error even after giving it admin privileges. Eventually, after messing around with it enough, it just started working with the original commands. Might have had something to do with restarting Command Prompt or deleting my environment and starting over.
