### ISSUE TITLE
arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit

### ISSUE THREAD

**Issue by andrey-genpracc** [oobabooga/text-generation-webui#4922]
### Describe the bug

When i use parameter --tensor_split 0,1 

```
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:Replaced attention with xformers_attention
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:LOADER: llama.cpp
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:TRUNCATION LENGTH: 2048
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:INSTRUCTION TEMPLATE: Alpaca
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:Loaded the model in 5.79 seconds.
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:Loading the extension "gallery"...
Dec 14 15:30:01 llm-dev-generator start_linux.sh[5618]: CUDA error 400 at /home/runner/work/llama-cpp-python-cuBLAS-wheels/llama-cpp-python-cuBLAS-wheels/vendor/llama.cpp/ggml-cuda.cu:7172: invalid resource handle
Dec 14 15:30:01 llm-dev-generator start_linux.sh[5618]: current device: 1
Dec 14 15:30:01 llm-dev-generator start_linux.sh[5618]: /arrow/cpp/src/arrow/filesystem/s3fs.cc:2904:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit

```

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Set the parameter --tensor_split 0,1 and run
2. type smth in chat i error will appear

### Logs

```shell
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:Replaced attention with xformers_attention
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:LOADER: llama.cpp
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:TRUNCATION LENGTH: 2048
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:INSTRUCTION TEMPLATE: Alpaca
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:Loaded the model in 5.79 seconds.
Dec 14 14:56:13 llm-dev-generator start_linux.sh[5618]: 2023-12-14 14:56:13 INFO:Loading the extension "gallery"...
Dec 14 15:30:01 llm-dev-generator start_linux.sh[5618]: CUDA error 400 at /home/runner/work/llama-cpp-python-cuBLAS-wheels/llama-cpp-python-cuBLAS-wheels/vendor/llama.cpp/ggml-cuda.cu:7172: invalid resource handle
Dec 14 15:30:01 llm-dev-generator start_linux.sh[5618]: current device: 1
Dec 14 15:30:01 llm-dev-generator start_linux.sh[5618]: /arrow/cpp/src/arrow/filesystem/s3fs.cc:2904:  arrow::fs::FinalizeS3 was not called even though S3 was initialized.  This could lead to a segmentation fault at exit
```

### System Info

```shell
i use snapshot-2023-12-10 version . 2x NVIDIA L4 , CUDA 12.1
```

**Comment by RobViren** [comment]
Hello, this happened to me a lot. When a laptop goes into hibernate you need to reload the NVIDIA kernel module. 
```bash
sudo rmmod nvidia_uvm
sudo modprobe nvidia_uvm
```

You can put this in a script and run it after the system wakes up. Let me know if that works.

**Comment by andrey-genpracc** [comment]
> --tensor_split 0,1

Its a server without hibernation . i tried to reload  nvidia_uvm module but it's didn't help me

**Comment by andrey-genpracc** [comment]
That format of parameter solved my problem --tensor_split 50,50
