### ISSUE TITLE
Update the one-click-installers to support 4bit llama models (bandaid solution included)

### ISSUE THREAD

**Issue by ClayShoaf** [oobabooga/text-generation-webui#520]
**Description**

I think the recent developments warrant a new release of the one-click-installers. I know you guys are probably super busy, so I'm not trying to rush you. I mostly wanted to make this issue so I could include a batch file I made that will make it work natively for windows users today. Hopefully this helps someone out

**Additional Context**

If you are getting CUDA errors on windows native, I finally got it running on my machine and made a batch file that should hopefully work for you as well. Check it out here: https://github.com/ClayShoaf/oobabooga-one-click-bandaid

**Comment by luiscosio** [comment]
You should add this to the wiki.

**Comment by ClayShoaf** [comment]
I want to make sure it works on at least one other person's computer first. Otherwise it'll just be another failed "works on my machine" moment for whoever stumbles across it in desparation.

**Comment by ClayShoaf** [comment]
> You should add this to the wiki.

Ok, it looks like it's actually working for other people. How do I edit the wiki? Should I just @oobabooga?

**Comment by oobabooga** [comment]
I have added it to the README for now under https://github.com/oobabooga/text-generation-webui#alternative-one-click-installers

Thanks for sharing your script by the way, @ClayShoaf! I am not good at writing Windows batch scripts.

**Comment by zyxpixel** [comment]
It is great for me.
Small bug report: In my case, the last two lines doesn't work:

> sed -i 's/call python server.py --auto-devices --cai-chat/call python server.py --auto-devices --cai-chat --gptq-bits 4 --gptq-model-type LLaMa/g' start-webui.bat
> install.bat

It just can't find the two files. I manually copied the content and executed the install.bat. It may need to revise relative path or permission.

Performance improvement (laptop 3070, 8GB):
13B 8bit 0.3t/s
7b 8bit 1t/s
7b 4bit 2.5t/s

**Comment by ClayShoaf** [comment]
> It just can't find the two files

Weird that it would find all of the other files. Is it kicking an error message? I thought about doing `./` but I wasn't sure if it should have been `.\` instead for windows. I'm not intimately familiar with conda environments so I wasn't sure if they preffered windows formatting or *nix formatting, It worked without errors on my computer so I figured everything would work fine. 

Are you using Windows 10 or 11?

**Comment by zyxpixel** [comment]
> Are you using Windows 10 or 11?

In win11. If I just run bandaid.bat the CMD works under C:\Windows\System32.

C:\Windows\System32>install.bat
'install.bat' is not recognized as an internal or external command,
operable program or batch file.

If use

@echo on
cd /d %~d0
cd %~dp0
install.bat
pause

It is OK.

**Comment by zyxpixel** [comment]
> 

My files are like D:\LLaMA\bandaid.bat and D:\LLaMA\install.bat
**cd /d %~d0** means to enter the bat file‘s drive letter(here, D:)
**cd %~dp0** means to enter the bat file‘s path(here, D:\LLaMA)
All that means to run “D:\LLaMA\install.bat”

I don't know why, but if I right-click D:\LLaMA\bandaid.bat and run as administrator, the cmd starts from C:\Windows\System32,
 "C:\Windows\System32>install.bat" is not work but “D:\LLaMA>install.bat” works.

The test result is like this:

> C:\Windows\System32>set INSTALL_ENV_DIR=C:\Windows\System32\installer_files\env
> 
> C:\Windows\System32>set PATH=C:\Windows\System32\installer_files\env;C:\Windows\System32\installer_files\env\Library\bin;C:\Windows\System32\installer_files\env\Scripts;C:\Windows\System32\installer_files\env\Library\usr\bin;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;;C:\Program Files\Docker\Docker\resources\bin;C:\Users\zyx\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\zyx\AppData\Local\Programs\Python\Python310\;C:\Users\zyx\AppData\Local\Microsoft\WindowsApps;C:\Users\zyx\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\zyx\.dotnet\tools;C:\Program Files\CMake\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\lib;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\libnvvp;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64;C:\Users\zyx\AppData\Roaming\npm
> 
> C:\Windows\System32>call conda activate
> AAAAA
> '.' is not recognized as an internal or external command,
> operable program or batch file.
> BBBBB
> '.\hello.bat' is not recognized as an internal or external command,
> operable program or batch file.
> CCCCC
> 'hello.bat' is not recognized as an internal or external command,
> operable program or batch file.
> Press any key to continue . . .

**Comment by ClayShoaf** [comment]
>I don't know why, but if I right-click D:\LLaMA\bandaid.bat and run as administrator, the cmd starts from C:\Windows\System32
Have you tried running it not as administrator? I didn't even consider running as admin.

**Comment by ClayShoaf** [comment]
Can you try putting `cmd /k` as the last command in the `test.bat`. I want to see if conda actually activated when using `CALL conda.bat activate`. If it did, it should say `(base)` at the beginning of your command prompt. I think I'll end up making a second "windows 11" batch file.

**Comment by zyxpixel** [comment]
> 

Not as administrator

> BBBBB
> hello world
> CCCCC
> hello world
> 'cmd' is not recognized as an internal or external command,
> operable program or batch file.
> Press any key to continue . . .

As administrator

> BBBBB
> '.\hello.bat' is not recognized as an internal or external command,
> operable program or batch file.
> CCCCC
> 'hello.bat' is not recognized as an internal or external command,
> operable program or batch file.
> (base) C:\Windows\System32>

**Comment by ClayShoaf** [comment]
Haha, that is ridiculous. It's gonna be tough for me to get something that I'm confident functions correctly in Windows 11 without having a Windows 11 system of my own. If you can make something that functions as a .bat file and make a PR to my repo, that would be awesome. I would just ask that you make sure it works as it should, i.e.:
>fresh unzip
>run install.bat
>run bandaid-win11.bat

and they have a functioning install.

**Comment by jllllll** [comment]
@zyxpixel Can you try the install script in my repo? https://github.com/jllllll/one-click-installers
The bandaid fixes are incorporated and it shouldn't matter if it is run as admin or not.
I'm holding off on submitting a pr until someone else can test it and the immanent gptq changes are added to the webui.

**Comment by zyxpixel** [comment]
> Haha, that is ridiculous. 

It is not your bandaid's problem. I tried the original one-click-installer again, if it is not run as administrator, it can't access many commands like conda and curl:

> What is your GPU?
> 
> A) NVIDIA
> B) None (I want to run in CPU mode)
> 
> Input> a
> "Downloading micromamba from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe to D:\LLAMA\installer_files\mamba\micromamba.exe"
> 'curl' is not recognized as an internal or external command,
> operable program or batch file.
> Micromamba version:
> Access is denied.
> Access is denied.
> "Packages to install: torchvision=0.14.1 torchaudio=0.13.1 pytorch-cuda=11.7 conda git"
> Access is denied.
> Access is denied.
> "There was a problem while installingtorchvision=0.14.1 torchaudio=0.13.1 pytorch-cuda=11.7 conda git using micromamba. Cannot continue."
> Press any key to continue . . .

But if it is run as administrator(from C:\Windows\System32\), it will put files like:

C:\Windows\System32\installer_files
C:\Windows\System32\text-generation-webui
D:\LLaMA\start-webui.bat
D:\LLaMA\install.bat

They are not in the same position(but I think your bandaid works when all of them will woek well?), so when I run your bandaid from C:\Windows\System32\ it cannot find things under D:\LLaMA\,  while run it from D:\LLaMA it can not find conda and other things under C:\Windows\System32\installer_files.

For me the solution is to run half of your bandaid from  C:\Windows\System32\, and manually run another half under D:\LLaMA\, but I am not sure if it is a common solution.

**Comment by jllllll** [comment]
> 'curl' is not recognized as an internal or external command

This means that C:\Windows\System32 is not in your PATH environment variable. This is odd, because that is supposed to be a default entry. It is an easy enough addition to the install script at least.

**Comment by zyxpixel** [comment]
>The bandaid fixes are incorporated and it shouldn't matter if it is run as admin or not.

Not as admin:

> What is your GPU?
> 
> A) NVIDIA
> B) None (I want to run in CPU mode)
> 
> Input> a
> "Downloading Micromamba from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe to E:\LLAMA test\installer_files\mamba\micromamba.exe"
> 'curl' is not recognized as an internal or external command,
> operable program or batch file.
> Micromamba version:
> Access is denied.
> Micromamba not found.
> Press any key to continue . . .

and a error window 'This app cannot run in your PC'

**Comment by jllllll** [comment]
> and a error window 'This app cannot run in your PC'

Just updated the script. Try it again.

**Comment by zyxpixel** [comment]
> > 'curl' is not recognized as an internal or external command
> 
> This means that C:\Windows\System32 is not in your PATH environment variable. This is odd, because that is supposed to be a default entry. It is an easy enough addition to the install script at least.

Thanks, the original one-click-installer works well now, with C:\Windows\System32 in PATH environment variable.
But your updated script gives:

> A) NVIDIA
> B) None (I want to run in CPU mode)
> 
> Input> a
> "Downloading Micromamba from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe to E:\LLAMA test\installer_files\mamba\micromamba.exe"
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> 100 8028k  100 8028k    0     0  2055k      0  0:00:03  0:00:03 --:--:-- 2706k
> Micromamba version:
> 0.26.0
> 'E:\LLAMA' is not recognized as an internal or external command,
> operable program or batch file.
> critical libmamba Cannot activate, prefix does not exist at: E:\LLAMA test\installer_files\env
> E:\LLAMA test\installer_files\env not found.
> Press any key to continue . . .

**Comment by jllllll** [comment]
> > > 'curl' is not recognized as an internal or external command
> > 
> > 
> > This means that C:\Windows\System32 is not in your PATH environment variable. This is odd, because that is supposed to be a default entry. It is an easy enough addition to the install script at least.
> 
> Thanks, the original one-click-installer works well now, with C:\Windows\System32 in PATH environment variable. But your updated script gives:
> 
> > A) NVIDIA
> > B) None (I want to run in CPU mode)
> > Input> a
> > "Downloading Micromamba from https://github.com/cmdr2/stable-diffusion-ui/releases/download/v1.1/micromamba.exe to E:\LLAMA test\installer_files\mamba\micromamba.exe"
> > % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
> > Dload  Upload   Total   Spent    Left  Speed
> > 0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> > 100 8028k  100 8028k    0     0  2055k      0  0:00:03  0:00:03 --:--:-- 2706k
> > Micromamba version:
> > 0.26.0
> > 'E:\LLAMA' is not recognized as an internal or external command,
> > operable program or batch file.
> > critical libmamba Cannot activate, prefix does not exist at: E:\LLAMA test\installer_files\env
> > E:\LLAMA test\installer_files\env not found.
> > Press any key to continue . . .

Must have forgot to put quotes somewhere. I'll go through the script and quote everything just to be sure.

**Comment by jllllll** [comment]
@zyxpixel I think the script is fixed now. CMD hates dealing with spaces in file paths. Shouldn't be an issue now.

**Comment by zyxpixel** [comment]
> @zyxpixel I think the script is fixed now. CMD hates dealing with spaces in file paths

Yeah it works! You solve all the problems in my pc, I try a fresh install and it works in both 4bit and 8bit.
They seems to need different .bats to start webUI, as @ClayShoaf added, I need to add this in bat for 4bit:

> call python server.py --auto-devices --chat --auto-launch  --gptq-bits 4 --gptq-model-type LLaMa

and another setting for 8bit:

> call python server.py --auto-devices --chat --auto-launch 

If I don't use "--gptq-bits 4 --gptq-model-type LLaMa" it will show the 4bit models but give error in loading.

**Comment by jllllll** [comment]
> > @zyxpixel I think the script is fixed now. CMD hates dealing with spaces in file paths
> 
> Yeah it works! You solve all the problems in my pc, I try a fresh install and it works in both 4bit and 8bit. They seems to need different .bats to start webUI, as @ClayShoaf added, I need to add this in bat for 4bit:
> 
> > call python server.py --auto-devices --chat --auto-launch  --gptq-bits 4 --gptq-model-type LLaMa
> 
> and another setting for 8bit:
> 
> > call python server.py --auto-devices --chat --auto-launch

You can see all of the launch arguments and what they do on the main page. Hopefully, a way to auto-detect model types will be developed in the future so that we don't have to bother with all of that.

**Comment by ClayShoaf** [comment]
> @zyxpixel Can you try the install script in my repo? https://github.com/jllllll/one-click-installers The bandaid fixes are incorporated and it shouldn't matter if it is run as admin or not. I'm holding off on submitting a pr until someone else can test it and the immanent gptq changes are added to the webui.

So, if someone runs this script, then they don't have to run my bandaid batch file anymore and I can stop worrying about maintaining it?

**Comment by jllllll** [comment]
> > @zyxpixel Can you try the install script in my repo? https://github.com/jllllll/one-click-installers The bandaid fixes are incorporated and it shouldn't matter if it is run as admin or not. I'm holding off on submitting a pr until someone else can test it and the immanent gptq changes are added to the webui.
> 
> So, if someone runs this script, then they don't have to run my bandaid batch file anymore and I can stop worrying about maintaining it?

At least until a new bandaid is needed...

**Comment by ClayShoaf** [comment]
> > > @zyxpixel Can you try the install script in my repo? https://github.com/jllllll/one-click-installers The bandaid fixes are incorporated and it shouldn't matter if it is run as admin or not. I'm holding off on submitting a pr until someone else can test it and the immanent gptq changes are added to the webui.
> > 
> > 
> > So, if someone runs this script, then they don't have to run my bandaid batch file anymore and I can stop worrying about maintaining it?
> 
> At least until a new bandaid is needed...

Awesome!

**Comment by ClayShoaf** [comment]
I linked your repo at the top of me README, @jllllll

**Comment by ClayShoaf** [comment]
@oobabooga I won't be able to maintain my repo for a while. I'm gonna close this issue because I don't know when I'll be able to get back. @jllllll seems to have incorporated the whole thing into his fork. I don't know what the status is, but @jllllll someone put in an issue for your fork on my repo. I @'d you in it.

**Comment by oobabooga** [comment]
Thank you for your contribution, @ClayShoaf! I will acknowledge both you and @jllllll once the one click installer is merged.

I still haven't been able to test the PR because of a cryptic micromamba error that I am getting on my Windows 11 installation (it also happens with the current one click installer).

**Comment by ClayShoaf** [comment]
@oobabooga Here's what the person in my issues said worked for them: https://github.com/oobabooga/text-generation-webui/issues/15#issuecomment-1404001472

**Comment by jllllll** [comment]
> Thank you for your contribution, @ClayShoaf! I will acknowledge both you and @jllllll once the one click installer is merged.
> 
> I still haven't been able to test the PR because of a cryptic micromamba error that I am getting on my Windows 11 installation (it also happens with the current one click installer).

What is the error? I experienced a whole range of errors when I was switching the installer over to using only micromamba.
While micromamba technically supports CMD, it doesn't do it well. On top of that, CMD is buggy and inconsistent with it's functionality. One issue I had was that one specific call command was parsing text differently than other, nearly identical, commands. Turned out, that one command was behaving differently because it was in a code block (). No clue why only that one specific instance of `call` was breaking and not the others. Honestly, if we want consistent behavior from an installer, then we should switch to using Powershell rather than CMD.

**Comment by oobabooga** [comment]
This is the error:

```
...
pytorch                                              1.3GB @  18.1MB/s 1m:2.7s
libxcb                                               1.3MB @  19.3kB/s  0.4s
pysocks                                             19.3kB @ 278.0 B/s  0.1s
python                                              15.9MB @ 227.8kB/s  0.5s
cuda-nvtx                                           43.9kB @ 622.0 B/s  1.1s
libcurand-dev                                       51.5MB @ 712.0kB/s  5.0s
libcusolver-dev                                     90.8MB @   1.2MB/s  7.0s
cuda-sanitizer-api                                  13.2MB @ 157.0kB/s 36.6s
Linking pytorch-mutex-1.0-cuda
Linking git-2.40.0-h57928b3_1
Linking ca-certificates-2022.12.7-h5b45459_0
Linking ucrt-10.0.22621.0-h57928b3_0
Linking msys2-conda-epoch-20160418-1
Linking mkl-include-2022.1.0-h6a75c08_874
Linking intel-openmp-2023.0.0-h57928b3_25922
Linking python_abi-3.10-3_cp310
Linking vs2015_runtime-14.34.31931-h4c5c07a_10
Linking m2w64-libwinpthread-git-5.0.0.4634.697f757-2
warning  libmamba Invalid package cache, file 'C:\Users\me\Downloads\one-click-installers-oobabooga-windows\one-click-installers-oobabooga-windows\installer_files\mamba\pkgs\m2w64-libwinpthread-git-5.0.0.4g
error    libmamba Cannot find a valid extracted directory cache for 'm2w64-libwinpthread-git-5.0.0.4634.697f757-2.tar.bz2'
```

This started happening after I reinstalled Windows 11 a few weeks ago. I have no idea what it is about...

All the downloads go fine. This only happens in this "Linking" stage.

**Comment by jllllll** [comment]
@oobabooga Change the `MICROMAMBA_DOWNLOAD_URL` variable in the script to:
https://github.com/mamba-org/micromamba-releases/releases/latest/download/micromamba-win-64

This will download the latest version of micromamba which may work better. If it works, I'll update the script to use that url.

**Comment by oobabooga** [comment]
I have tried it with this official micromamba link and got the same error, both running as admin and not. It's nice to use the official link though (I was not aware of this download option).

It's possible that this is an error that will only happen in my machine.

**Comment by jllllll** [comment]
> I have tried it with this official micromamba link and got the same error, both running as admin and not. It's nice to use the official link though (I was not aware of this download option).
> 
> It's possible that this is an error that will only happen in my machine.

I doubt it would help your issue, but I made a Powershell script as an alternative to the main batch script.
https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-powershell

**Comment by oobabooga** [comment]
Same issue after running this command, or running as administrator.

I have found few references to this `warning  libmamba Invalid package cache` error:

| Source | Description |
|--------|---------|
| https://github.com/KoboldAI/KoboldAI-Client/issues/155  | Claims that the problem was him "using ntfs". Maybe he can help us? @CrocodileCroco |
| https://github.com/mamba-org/mamba/issues/1700 | Here it is said that the problem was the presence of a symlink in the package. |

Thanks for the patience by the way, I know how hard it is to debug a problem happening in someone else's computer.

**Comment by oobabooga** [comment]
Is it possible to use micromamba to install conda and then proceed with the rest of the installation using conda? Just an idea, maybe that would be more reliable if that makes sense.

**Comment by jllllll** [comment]
> Is it possible to use micromamba to install conda and then proceed with the rest of the installation using conda? Just an idea, maybe that would be more reliable if that makes sense.

That is what the original installer was doing. If we need to, we can switch to miniconda, which is just conda without some of the more advanced functionality that we don't need. It's an easy enough change to make. While I'm making that, try adding `msys2::m2w64-libwinpthread-git` to the package list in the script.

**Comment by jllllll** [comment]
@oobabooga Here is an installer script that uses Micromamba to download and setup Conda. Conda is then used for everything else and Micromamba is deleted as it is no longer necessary.
https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-conda-bootstrap

**Comment by oobabooga** [comment]
With the new conda installer, I got a variation of the same error while trying to install conda:

```
[+] 20.6s
Downloading      -------------------------------------------------------------------------------------------------------Linking vs2015_runtime-14.27.29016-h5e58377_2
Linking ca-certificates-2023.01.10-haa95532_0
Linking vc-14.2-h21ff451_1
Linking sqlite-3.41.1-h2bbff1b_0
Linking libffi-3.4.2-hd77b12b_6
Linking bzip2-1.0.8-he774522_0
Linking tk-8.6.12-h2bbff1b_0
Linking openssl-1.1.1t-h2bbff1b_0
Linking xz-5.2.10-h8cc25b3_1
Linking zlib-1.2.13-h8cc25b3_0
Linking tzdata-2022g-h04d1e81_0
Linking python-3.10.9-h966fe2a_2
warning  libmamba Invalid package cache, file 'C:\Users\me\Downloads\one-click-installers-oobabooga-windows-conda-bgerror    libmamba Cannot find a valid extracted directory cache for 'python-3.10.9-h966fe2a_2.tar.bz2'
critical libmamba Package cache error.

Removing Micromamba

```

So now we know that the problem is not

* Permissions
* Using cmd instead of powershell
* The `m2w64-libwinpthread-git` package in particular

**Comment by jllllll** [comment]
> So now we know that the problem is not
> 
>     * Permissions
> 
>     * Using cmd instead of powershell
> 
>     * The `m2w64-libwinpthread-git` package in particular

We also know that it isn't an issue with making symlinks or hardlinks. I had set micromamba to only copy the conda files.

**Comment by jllllll** [comment]
I might try creating a local installation of miniconda. Then there won't be any use of micromamba.

**Comment by jllllll** [comment]
@oobabooga I made an installer that utilizes Miniconda. This biggest downside to this method is that Miniconda will refuse to install under a path containing spaces. If this works on your system, and you are fine with the space issue, then I'll merge this version into the pull request and keep the other versions as a backup.
https://github.com/jllllll/one-click-installers/tree/oobabooga-windows-miniconda

**Comment by jllllll** [comment]
> The error happens because the `%MINICONDA_DIR%\Scripts` is never created.
> 
> There is a `/S` flag, which I guess stands for Silent mode. If I remove it, the miniconda installer GUI launches and prompts me to install miniconda in a default folder like `C:/Program files/`.

`%MINICONDA_DIR%\Scripts` is a necessary folder for the functionality of miniconda. It contains the conda executable, among other things. If that folder doesn't exist, then miniconda either didn't install or didn't install correctly. I thought about just using the GUI, but then it wouldn't be a one-click installer anymore. You should try installing it outside of the `Users` folder and see if that makes a difference. The Conda devs put a lot of restrictions on where miniconda can be installed.

**Comment by oobabooga** [comment]
I have updated the README with mentions to @jllllll and @ClayShoaf. Thanks again for your contributions, this updated one-click installer is enormously useful.

https://github.com/oobabooga/text-generation-webui#installation
