### ISSUE TITLE
Unable to Unload LoRA

### ISSUE THREAD

**Issue by generic-username0718** [oobabooga/text-generation-webui#524]
### Describe the bug

I'm unable to UNLOAD Alpaca Lora

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. python3 server.py --load-in-8bit --gpu-memory 16 25 --cai-chat --listen --model llama-30b --extensions llama_prompts character_bias
2. Load alpaca-30b lora using webUI
3. Unload alpaca-30b lora using webUI

OOM on "Reloading the model to remove the LoRA..."

### Screenshot

![image](https://user-images.githubusercontent.com/126929561/227389825-30d0217a-8638-40ca-add7-6e1fb4bd4019.png)

### Logs

```shell
(textgen2) user@user-System-Product-Name:~/Documents/ooba/2/text-generation-webui$ python3 server.py --load-in-8bit --gpu-memory 16 25 --cai-chat --listen --model llama-30b --extensions llama_prompts character_bias
Loading settings from settings.json...
Loading llama-30b...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: /home/user/anaconda3/envs/textgen2/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary /home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/bitsandbytes/libbitsandbytes_cuda117.so...
Loading checkpoint shards: 100%|████████████████| 61/61 [04:59<00:00,  4.91s/it]
Loaded the model in 300.20 seconds.
Loading the extension "llama_prompts"... Ok.
Loading the extension "character_bias"... Ok.
Loading the extension "gallery"... Ok.
/home/user/.local/lib/python3.10/site-packages/gradio/deprecation.py:40: UserWarning: The 'type' parameter has been deprecated. Use the Number component instead.
  warnings.warn(value)
Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Adding the LoRA alpaca-lora-30b to the model...
Reloading the model to remove the LoRA...
Loading llama-30b...
Loading checkpoint shards:  20%|███▏            | 12/61 [00:32<02:11,  2.69s/it]
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.10/site-packages/gradio/routes.py", line 374, in run_predict
    output = await app.get_blocks().process_api(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 1017, in process_api
    result = await self.call_function(
  File "/home/user/.local/lib/python3.10/site-packages/gradio/blocks.py", line 835, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/user/.local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/user/Documents/ooba/2/text-generation-webui/server.py", line 73, in load_lora_wrapper
    add_lora_to_model(selected_lora)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/LoRA.py", line 14, in add_lora_to_model
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/models.py", line 159, in load_model
    model = AutoModelForCausalLM.from_pretrained(checkpoint, **params)
  File "/home/user/.local/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 471, in from_pretrained
    return model_class.from_pretrained(
  File "/home/user/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2646, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/home/user/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2969, in _load_pretrained_model
    new_error_msgs, offload_index, state_dict_index = _load_state_dict_into_meta_model(
  File "/home/user/.local/lib/python3.10/site-packages/transformers/modeling_utils.py", line 676, in _load_state_dict_into_meta_model
    set_module_8bit_tensor_to_device(model, param_name, param_device, value=param)
  File "/home/user/.local/lib/python3.10/site-packages/transformers/utils/bitsandbytes.py", line 70, in set_module_8bit_tensor_to_device
    new_value = bnb.nn.Int8Params(new_value, requires_grad=False, has_fp16_weights=has_fp16_weights).to(device)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 196, in to
    return self.cuda(device)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/bitsandbytes/nn/modules.py", line 160, in cuda
    CB, CBt, SCB, SCBt, coo_tensorB = bnb.functional.double_quant(B)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/bitsandbytes/functional.py", line 1621, in double_quant
    out_col = torch.zeros(A.shape, device=device, dtype=torch.int8)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 114.00 MiB (GPU 0; 23.69 GiB total capacity; 21.84 GiB already allocated; 98.88 MiB free; 22.84 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
5600X in Asus TUF X570
64GB DDR4 3600 RAM
2x3090w/NVLINK
```

**Comment by oobabooga** [comment]
See if this solved it https://github.com/oobabooga/text-generation-webui/commit/bf22d16ebcee96430d6845c9786bbdab5e74af17

**Comment by generic-username0718** [comment]
Yeah that fixed it
