### ISSUE TITLE
Error when using --load-in-8bit: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by Pounix01** [oobabooga/text-generation-webui#53]
I've been trying to load Pyg 2.7B model in 8-bit mode using my GTX 980ti on Windows 10, I am aware 8-bit mode is not really supported on pascal and older cards, though I have seen some people be able to do it. I followed https://github.com/oobabooga/text-generation-webui/issues/20#issuecomment-1411650652, and I was able to get rid of the 'CUDA Setup failed despite GPU being available.' error I had earlier, however a new one arose, here is the log:

```
(textgen) C:\Users\Admin\text-generation-webui>python server.py --load-in-8bit --cai-chat --no-stream
Loading pygmalion-2.7b...

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
Error no kernel image is available for execution on the device at line 479 in file D:\ai\tool\bitsandbytes\csrc\ops.cu
```

Any idea on how to solve this issue?

**Comment by oobabooga** [comment]
Related to #42

There are two separate issues at play: 

1. bitsandbytes doesn't work out of the box on Windows
2. bitsandbytes doesn't work on older cards

**Comment by Pounix01** [comment]
Maybe I missed an additional important step where I have to download 'prebuilt bitandbytes for older GPUs' as mentioned in https://github.com/oobabooga/text-generation-webui/issues/20#issuecomment-1411820570.

So I tried downloading the `libbitsandbytes_cudaall.dll` file from https://github.com/james-things/bitsandbytes-prebuilt-all_arch, redirecting main.py to the `libbitsandbytes_cudaall.dll` instead of `libbitsandbytes_cuda116.dll`, however I am getting the `CUDA Setup failed despite GPU being available.` error again, then I tried to replace the `libbitsandbytes_cuda116.dll` with `libbitsandbytes_cudaall.dll` by renaming the cudaall file to `libbitsandbytes_cuda116.dll`, however I am now getting the `no kernel image` error again. I am not sure what to do now, it does seem like bitsandbytes is having a hard time working with windows and my gpu.

**Comment by Ph0rk0z** [comment]
It's out.. you need a new DLL: https://github.com/TimDettmers/bitsandbytes/releases/tag/0.37.0

**Comment by Pounix01** [comment]
Update: I fixed the kernel image error. I thought bitsandbytes was on the newest 0.37 version but I was on 0.36, so I updated it. This still didn't fix the issue, but I saw a new 0.37 .dll build was released here (didn't saw it before) https://github.com/james-things/bitsandbytes-prebuilt-all_arch so I tried it out and the error is gone.

However, now I have a `probability tensor contains either `inf`, `nan` or element < 0` error, the same one as https://github.com/oobabooga/text-generation-webui/issues/42#issuecomment-1416714660, I have no clue what to do from here so I will just hope someone will find a solution for this.

**Comment by lugangqi** [comment]
My M40 24g runs ExLlama the same way, 4060ti 16g works fine under cuda12.4. M40 seems that the author did not update the kernel compatible with it, I also asked for help under the ExLlama2 author yesterday, I do not know whether the author to fix this compatibility problem, M40 and 980ti with the same architecture core computing power 5.2 to meet cuda12.4
