### ISSUE TITLE
Not recovering from OOM

### ISSUE THREAD

**Issue by generic-username0718** [oobabooga/text-generation-webui#610]
### Describe the bug

Out of memory crashes don't recover like they used to

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

python3 server.py --wbits 4 --gpu-memory 15 19 --listen --model llama-65b --extensions api character_bias --groupsize 128

### Logs

```shell
Output generated in 8.74 seconds (1.03 tokens/s, 9 tokens, context 1443)
Exception in thread Thread-11 (gentask):
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/callbacks.py", line 63, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "/home/user/Documents/ooba/2/text-generation-webui/modules/text_generation.py", line 222, in generate_with_callback
    shared.model.generate(**kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/generation/utils.py", line 1462, in generate
    return self.sample(
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/generation/utils.py", line 2478, in sample
    outputs = self(
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 765, in forward
    outputs = self.model(
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 614, in forward
    layer_outputs = decoder_layer(
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 321, in forward
    hidden_states = self.mlp(hidden_states)
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/anaconda3/envs/textgen2/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 151, in forward
    return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
  File "/home/user/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/.local/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/user/Documents/ooba/2/text-generation-webui/repositories/GPTQ-for-LLaMa/quant.py", line 374, in forward
    x = torch.matmul(x, weights.to(x.dtype))
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 344.00 MiB (GPU 1; 23.67 GiB total capacity; 21.64 GiB already allocated; 258.38 MiB free; 22.35 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

### System Info

```shell
5600X
3090
```

**Comment by generic-username0718** [comment]
I reset my head to 57345b8f30fcaf5eef2a5be2b4c239d51750a6ba and it fixed it... you must have changed something today... I'm guessing it was the "stop" commit...

**Comment by oobabooga** [comment]
If you are not using the Stop button, the stop commit doesn't change anything

**Comment by generic-username0718** [comment]
... I am using the stop button... that's how I recover from OOM... now it's just stuck on the screen... no way to recover except restarting the server...

![image](https://user-images.githubusercontent.com/126929561/228345191-b99f95bf-f71a-4ee2-8624-bee40f07678f.png)

**Comment by oobabooga** [comment]
I think that this should have solved it without the need to use the Stop button

https://github.com/oobabooga/text-generation-webui/commit/304f812c637f5494e6c42d296040f0506d9194a1

**Comment by generic-username0718** [comment]
Indeed it does appear that way... there's no real indication to the user that it hit OOM but if I try again it seems to work... An error like `Error: Out of Memory Exception. Please reduce max_new_tokens` might be helpful. Thanks

**Comment by neuhaus** [comment]
I have the same issue as of today, i get OOM eventually when running Llama-65b on two RTX 3090 and then the model will only generate single words responses until i use the "clear history" function.

**Comment by oobabooga** [comment]
@neuhaus Try reducing the value of the "maximum prompt size in tokens" variable
