### ISSUE TITLE
not working since commit 31f04dc bitsandbytes problem

### ISSUE THREAD

**Issue by Marc899** [oobabooga/text-generation-webui#614]
### Describe the bug

Starting with commit 31f04dc I am getting a lot of CUDA errors related to bitsandbytes when running the start-webui.bat

RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues

Reverting to 966168b makes it run again.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Update to the latest version and run the start-webui.bat

### Logs

```shell
RuntimeError:
        CUDA Setup failed despite GPU being available. Inspect the CUDA SETUP outputs above to fix your environment!
        If you cannot find any issues and suspect a bug, please open an issue with detals about your environment:
        https://github.com/TimDettmers/bitsandbytes/issues
```

### System Info

```shell
Windows 11 64bit
RTX 3090
```

**Comment by oivio** [comment]
I can confirm the same issue on my side
Windows 10
RTX4080
CUDA 11.7.0_516.01

**Comment by RJSprod** [comment]
I'm facing the exact same issue, windows 11 w/3090. The libcuda and libcudart files requested don't seem to exist on my system.

**Comment by bmoconno** [comment]
I was having the same issue, once I found this and saw everyone having it seemed to be using windows, I thought this was probably the culprit, it fixed the issue for me:

from [how_to_install_llama_8bit_and_4bit](https://www.reddit.com/r/LocalLLaMA/comments/11o6o3f/how_to_install_llama_8bit_and_4bit/)

>6. Download [libbitsandbytes_cuda116.dll](https://github.com/DeXtmL/bitsandbytes-win-prebuilt) and put it in C:\Users\xxx\miniconda3\envs\textgen\lib\site-packages\bitsandbytes\

>7. In \bitsandbytes\cuda_setup\main.py search for: if not torch.cuda.is_available(): return 'libsbitsandbytes_cpu.so', None, None, None, None and replace with: if torch.cuda.is_available(): return 'libbitsandbytes_cuda116.dll', None, None, None, None

>8. In \bitsandbytes\cuda_setup\main.py search for this twice: self.lib = ct.cdll.LoadLibrary(binary_path) and replace with: self.lib = ct.cdll.LoadLibrary(str(binary_path))

After re-doing those steps, I ran into another issue that I believe was caused by #615, it was complaining about `kernel_switch_threshold` not being a valid argument or something while trying to use the llama 30b 128 model. To fix this I modified the `modules\GPTQ_loader.py` file by doing the follow:

* re-add `import llama` line under `sys.path.insert(0, str(Path("repositories/GPTQ-for-LLaMa")))`
* replace `load_quant = _load_quant` with `load_quant = llama.load_quant`
* replace `model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)` with `model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize)`

It's possible you won't need to modify the `modules\GPTQ_loader.py`, so try to load your model before making those changes.

**Comment by oobabooga** [comment]
8-bit should work more reliably with the new one-click installer

https://github.com/oobabooga/text-generation-webui#one-click-installers

**Comment by hdkiller** [comment]
I do have similar issue on linux, probably caused by #615 since if I revert changes as @bmoconno mentioned it loads llama.

`
===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
/home/hdkiller/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes-0.37.2-py3.10.egg/bitsandbytes/cuda_setup/main.py:136: UserWarning: /home/hdkiller/miniconda3/envs/textgen did not contain libcudart.so as expected! Searching further paths...
  warn(msg)
CUDA SETUP: CUDA runtime path found: /usr/local/cuda/lib64/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 121
CUDA SETUP: Loading binary /home/hdkiller/miniconda3/envs/textgen/lib/python3.10/site-packages/bitsandbytes-0.37.2-py3.10.egg/bitsandbytes/libbitsandbytes_cuda121.so...
Loading llama-7b-hf...
Found models/llama-7b-4bit.safetensors
Traceback (most recent call last):
  File "/home/hdkiller/text-generation-webui/server.py", line 273, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "/home/hdkiller/text-generation-webui/modules/models.py", line 101, in load_model
    model = load_quantized(model_name)
  File "/home/hdkiller/text-generation-webui/modules/GPTQ_loader.py", line 113, in load_quantized
    model = load_quant(str(path_to_model), str(pt_path), shared.args.wbits, shared.args.groupsize, kernel_switch_threshold=threshold)
  File "/home/hdkiller/text-generation-webui/modules/GPTQ_loader.py", line 36, in _load_quant
    make_quant(model, layers, wbits, groupsize, faster=faster_kernel, kernel_switch_threshold=kernel_switch_threshold)
TypeError: make_quant() got an unexpected keyword argument 'kernel_switch_threshold'`

**Comment by remghoost** [comment]
> It did work after removing the GPTQ-for-LLama directory and literally performing a new git clone and pip install. No idea why.

This worked for me as well.

Seems like a fairly common occurrence. Happens every few commits. 
Nice to know this fix works. 
I've had this problem before (a few weeks ago) and literally spent **days** trying to fix it.

Might make myself a quick script to automate this for fixing it in the future. haha.

**Comment by davidliudev** [comment]
Same issue for me too under Windows 11. Tried removing the GPTQ folder and it is not working. Had to temporarily revert to https://github.com/oobabooga/text-generation-webui/commit/966168bd2a8740d5548d7e3409745ab37decc09b

**Comment by gruevy** [comment]
> 8-bit should work more reliably with the new one-click installer
> 
> https://github.com/oobabooga/text-generation-webui#one-click-installers

Is there any reason that bitsandbytes fix from the prior comment isn't part of the typical installation? I have to do it every time and the webui won't even start up without out. I'm not the only one.

**Comment by StefanDanielSchwarz** [comment]
Same here, fresh WSL install, got the "TypeError: make_quant() got an unexpected keyword argument 'faster'" message when trying to load ozcur's alpaca-native-4bit.

Reverting to 966168b fixed it for me, too: `git reset --hard 966168bd2a8740d5548d7e3409745ab37decc09b`

**Comment by oobabooga** [comment]
It's necessary to clone the GPTQ-for-llama repository with

```
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa.git -b cuda
```

now. The default branch in that repository has been changed for one that breaks backward compatibility.

This has been updated in the one-click installer, which must be re-downloaded manually (just the install.bat script) https://github.com/oobabooga/one-click-installers/commit/85e4ec6e6becfb229c50688de242346d5f30c402

**Comment by StefanDanielSchwarz** [comment]
Excellent, that fixes it! 👍 Glad to be able to use the latest version of your text-generation-webui again (and special thanks for merging my PR ❤).

**Comment by hdkiller** [comment]
Seems like something going on in that `cuda` branch of `GPTQ-for-LLaMa` 

I had to revert to this commit.

```
git clone https://github.com/qwopqwop200/GPTQ-for-LLaMa.git -b cuda
git reset --hard b820805
python setup_cuda.py install
```

This is the [commit](https://github.com/qwopqwop200/GPTQ-for-LLaMa/commit/f1af89a611fd593074fc1390bb8663aee635e496#diff-2412c8e2f2672173555add3712f88691f77ae8bbe64a721738c08d93754e1be6) which removed a parameter from the function definition of make_quant which throws  the error @Azeirah had. 

This way now I am able to CPU offload llama:

` python3 server.py --listen --wbits 4 --groupsize 128 --pre_layer 30 --model llama-7b-4bit-128g`

**Comment by StefanDanielSchwarz** [comment]
Confirming that - both the problem and the workaround. Thanks @hdkiller for figuring out the correct commit to revert to.

**Comment by oobabooga** [comment]
Please use my fork of GPTQ-for-LLaMa. It corresponds to commit `a6f363e3f93b9fb5c26064b5ac7ed58d22e3f773` in the `cuda` branch. 

```console
# activate the conda environment
conda activate textgen

# remove the existing GPT-for-LLaMa
cd text-generation-webui/repositories
rm -rf GPTQ-for-LLaMa
pip uninstall quant-cuda

# reinstall
git clone https://github.com/oobabooga/GPTQ-for-LLaMa.git -b cuda
cd GPTQ-for-LLaMa
python setup_cuda.py install
```

I will keep using this until qwopqwop's branch stabilizes. Upstream changes will not be supported. This works with @USBhost's torrents for llama that are linked [here](https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-2-get-the-pre-converted-weights).
