### ISSUE TITLE
VRAM Usage Explodes With ExllamaV3_HF, But Not Vanilla ExllamaV3

### ISSUE THREAD

**Issue by Downtown-Case** [oobabooga/text-generation-webui#6922]
### Describe the bug

As the title says, when running an exl3 with a long context (say, Qwen 32B 4bpw, 55K context, Q4 cache), VRAM usage hovers just under 20GB when loading, but explodes past 24GB with long context requests (past ~8K).

### Is there an existing issue for this?

- [x] I have searched the existing issues

### Reproduction

Example command: `python server.py --listen --api --loader ExLlamav3_HF --model "nbeerbower_EVA-Gutenberg3-Qwen2.5-32B-exl3-4.0bpw-hb8" --n_ctx 56320 --cache_type q4 --nowebui`

Example model: https://huggingface.co/Downtown-Case/nbeerbower_EVA-Gutenberg3-Qwen2.5-32B-exl3-4.0bpw-hb8

Hit the server with increasingly large requests. They take up more and more VRAM, as if something is being allocated dynamically, there's a memory leak, or some similar issue. VRAM usage quickly blows up past 24GB even though the model loads at around 20GB (and statically allocates the KV cache up front).

Try any of the examples here: https://github.com/turboderp-org/exllamav3/tree/master/examples

Or the OpenAI API server here: https://github.com/turboderp-org/exllamav3/pull/22

And ExllamaV3 does not go past ~20GB of VRAM usage, even when processing the full 50K context. The VRAM usage is relatively static (barring a _small_ bump after the first generation). So this appears to be something specific to text-gen-web-ui's implementation.

### Screenshot

The model loads at 20GB:

![Image](https://github.com/user-attachments/assets/796e3e3d-5af3-46b2-b21f-f70ebd01426f)

### Logs

Working 4000 token, 8000 token input generation, then crash at 16000:

```shell

Output generated in 3.53 seconds (2.83 tokens/s, 10 tokens, context 3272, seed 496843076)
INFO:     127.0.0.1:52282 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:52282 - "OPTIONS /v1/token/encode HTTP/1.1" 200 OK
INFO:     127.0.0.1:52266 - "POST /v1/token/encode HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52266 - "OPTIONS /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:52282 - "POST /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:52282 - "OPTIONS /v1/token/encode HTTP/1.1" 200 OK
INFO:     127.0.0.1:52266 - "POST /v1/token/encode HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:52266 - "OPTIONS /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:52282 - "POST /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:60040 - "OPTIONS /v1/token/encode HTTP/1.1" 200 OK
INFO:     127.0.0.1:60042 - "POST /v1/token/encode HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:60042 - "OPTIONS /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:60040 - "POST /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:60040 - "OPTIONS /v1/completions HTTP/1.1" 200 OK
Output generated in 6.70 seconds (1.49 tokens/s, 10 tokens, context 6577, seed 1520967780)
INFO:     127.0.0.1:60042 - "POST /v1/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:60042 - "OPTIONS /v1/token/encode HTTP/1.1" 200 OK
INFO:     127.0.0.1:42686 - "POST /v1/token/encode HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:42686 - "OPTIONS /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:60042 - "POST /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:60042 - "OPTIONS /v1/token/encode HTTP/1.1" 200 OK
INFO:     127.0.0.1:42686 - "POST /v1/token/encode HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:42686 - "OPTIONS /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:60042 - "POST /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:34170 - "OPTIONS /v1/token/encode HTTP/1.1" 200 OK
INFO:     127.0.0.1:34180 - "POST /v1/token/encode HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:34180 - "OPTIONS /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:34170 - "POST /v1/internal/token-count HTTP/1.1" 200 OK
INFO:     127.0.0.1:34170 - "OPTIONS /v1/completions HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/home/alpha/AI/text-generation-webui/modules/text_generation.py", line 434, in generate_reply_HF
    output = shared.model.generate(**generate_params)[0]
             ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/transformers/generation/utils.py", line 2465, in generate
    result = self._sample(
        input_ids,
    ...<5 lines>...
        **model_kwargs,
    )
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/transformers/generation/utils.py", line 3431, in _sample
    outputs = self(**model_inputs, return_dict=True)
  File "/home/alpha/AI/text-generation-webui/modules/exllamav3_hf.py", line 149, in __call__
    self.ex_model.forward(
    ~~~~~~~~~~~~~~~~~~~~~^
        input_ids=seq_tensor[:-1].view(1, -1),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        }
        ^
    )
    ^
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/exllamav3/models/model.py", line 79, in forward
    x = module.forward(x, params)
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/exllamav3/modules/linear.py", line 272, in forward
    x = self.inner.forward(x, params, out_dtype)
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/exllamav3/modules/quant/exl3.py", line 88, in forward
    w = self.get_inner_weight_tensor()
  File "/home/alpha/AI/exui_v3/venv/lib/python3.13/site-packages/exllamav3/modules/quant/exl3.py", line 128, in get_inner_weight_tensor
    w = torch.zeros((self.in_features, self.out_features), dtype = torch.half, device = self.trellis.device)
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.45 GiB. GPU 0 has a total capacity of 23.57 GiB of which 91.00 MiB is free. Including non-PyTorch memory, this process has 23.47 GiB memory in use. 23.57 GiB allowed; Of the allocated memory 23.11 GiB is allocated by PyTorch, and 57.37 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
Output generated in 14.24 seconds (0.00 tokens/s, 0 tokens, context 13099, seed 2141618665)
```

### System Info

```shell
3090 24GB (empty, not hooked up to display)
Linux
Python 3.13
flash attention/torch 2.8
Latest text-gen-web-ui/exllamav3 built from source.
```

I tried looking through the forward pass and making some changes, but can't seem to identify the issue? Settings such as chunk size (set at the default 2048) seem correct.

**Comment by oobabooga** [comment]
It seems like making forward calls with exllamav3 is not as simple as I expected. I have made this change in the dev branch:

https://github.com/oobabooga/text-generation-webui/commit/ee0592473c16db1917c98a24ec24dce36fd00bed

Can you check if

1. This solves the issue, and
2. It doesn't introduce new issues?

**Comment by LPCTSTR** [comment]
> It seems like making forward calls with exllamav3 is not as simple as I expected. I have made this change in the dev branch:
> 
> [ee05924](https://github.com/oobabooga/text-generation-webui/commit/ee0592473c16db1917c98a24ec24dce36fd00bed)
> 
> Can you check if
> 
> 1. This solves the issue, and
> 2. It doesn't introduce new issues?

This fixed it for me! Thanks for the quick solution!

**Comment by Downtown-Case** [comment]
> It seems like making forward calls with exllamav3 is not as simple as I expected. I have made this change in the dev branch:
> 
> [ee05924](https://github.com/oobabooga/text-generation-webui/commit/ee0592473c16db1917c98a24ec24dce36fd00bed)
> 
> Can you check if
> 
> 1. This solves the issue, and
> 2. It doesn't introduce new issues?

Completely it, thanks for the super quick fix!

If something else goes wrong related to the commit, I'll make an issue, heh.

**Comment by oobabooga** [comment]
Thanks for the feedback, I'm glad it worked :)
