### ISSUE TITLE
Issue running Web-UI

### ISSUE THREAD

**Issue by Cashubia** [oobabooga/text-generation-webui#754]
I attempted the steps in the instructions.txt file but when i run the "start-webui.bat" file I'm presented with this.
```
CUDA SETUP: CUDA runtime path found: C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Traceback (most recent call last):
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1125, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._boo\tstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\lib\site-packages\transformers\trainer_callback.py", line 26, in <module>
    from .trainer_utils import IntervalStrategy, has_length
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\lib\site-packages\transformers\trainer_utils.py", line 47, in <module>
    import tensorflow as tf
  File "C:\Users\Cashubia\AppData\Roaming\Python\Python310\site-packages\tensorflow\__init__.py", line 37, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Cashubia\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\__init__.py", line 37, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Cashubia\AppData\Roaming\Python\Python310\site-packages\tensorflow\python\eager\context.py", line 25, in <module>
    from absl import logging
ModuleNotFoundError: No module named 'absl'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\text-generation-webui\server.py", line 13, in <module>
    from modules import chat, shared, training, ui
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\text-generation-webui\modules\training.py", line 70, in <module>
    class Callbacks(transformers.TrainerCallback):
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1115, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "C:\Users\Cashubia\Desktop\oobabooga-windows\installer_files\env\lib\site-packages\transformers\utils\import_utils.py", line 1127, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.trainer_callback because of the following error (look up to see its traceback):
No module named 'absl'
```

I've checked to see if the absl-py package is installed and as far as I know it is so I'm not sure what's causing this issue.

**Comment by jllllll** [comment]
Currently re-installing to test. There seems to have been an update to transformers that is causing issues: https://github.com/oobabooga/text-generation-webui/issues/753

**Comment by jllllll** [comment]
My setup works fine. This seems to be caused by transformers detecting your tensorflow install outside of the environment. This isn't the first time that a python module has gone outside of the virtual environment set up by Micromamba. If this keeps happening, we'll need to switch to using Miniconda as it is the more mature and widely used platform, even though it's slower.

As a workaround, try adding this to the start-webui script just before `call python server.py`:
```batch
set USE_TF=0
```

**Comment by Cashubia** [comment]
> My setup works fine. This seems to be caused by transformers detecting your tensorflow install outside of the environment. This isn't the first time that a python module has gone outside of the virtual environment set up by Micromamba. If this keeps happening, we'll need to switch to using Miniconda as it is the more mature and widely used platform, even though it's slower.
> 
> As a workaround, try adding this to the start-webui script just before `call python server.py`:
> 
> ```batchfile
> set USE_TF=0
> ```

Thanks, this worked perfectly!
