### ISSUE TITLE
Vicuna 13B: Can't determine model type from model name. Please specify it manually using --model_type argument

### ISSUE THREAD

**Issue by Gitterman69** [oobabooga/text-generation-webui#761]
### Describe the bug

`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading ggml-vicuna-13b...
Can't determine model type from model name. Please specify it manually using --model_type argument
Press any key to continue . . .
`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading ggml-vicuna-13b...
Can't determine model type from model name. Please specify it manually using --model_type argument
Press any key to continue . . .
`

### Logs

```shell
`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading ggml-vicuna-13b...
Can't determine model type from model name. Please specify it manually using --model_type argument
Press any key to continue . . .
`
```

### System Info

```shell
`===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: D:\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary D:\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading ggml-vicuna-13b...
Can't determine model type from model name. Please specify it manually using --model_type argument
Press any key to continue . . .
`
```

**Comment by Fictiverse** [comment]
--model_type llama

**Comment by Gitterman69** [comment]
![Uploading F00FA3EF-6A9F-49D5-A925-2BAA34FD4F9F.png…]()

**Comment by Gitterman69** [comment]
> edit your `start-webui.bat`
> and change this line :
> `call python server.py --auto-devices --cai-chat --model vicuna-13b-4bit-128g --wbits 4 --groupsize 128 --model_type llama`

Doesnt work - see screenshot :(

**Comment by Meathelix1** [comment]
> 

Remove the - between the words that is what fixed it for me. vicuna13b4bit128g

**Comment by YakuzaSuske** [comment]
i use this version. This model already has the Delta patched applied and it works fine for me. I can definitely tell this model is better than LLaMA 13B. It's outputs are of better quality from what i can tell. (i used chatbot mode)

**Comment by Pythonpa** [comment]
> ![2023-04-04 09_10_29-models](https://user-images.githubusercontent.com/113683801/229715540-d74a4c13-3b93-4afe-b302-603ad009c792.png)
> 
> Still: `Could not find the quantized model in .pt or .safetensors format, exiting...`
> 
> I think its looking for a .pt or .safetensor file.... you guys are using this model as well (https://huggingface.co/eachadea/ggml-vicuna-13b-4bit)??? im so confused hahaha

The same error,must find some .safttensors file,like StableDiffusion....

**Comment by CyberTimon** [comment]
I have the same issue `Loading vicuna13b4bit128g...
Could not find the quantized model in .pt or .safetensors format, exiting...`

**Comment by CyberTimon** [comment]
Oh quite fixed, I had to write everything in lowercaps. But now I get this error: 

`RuntimeError: Error(s) in loading state_dict for LlamaForCausalLM:
        size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([32001, 5120]) from checkpoint, the shape in current model is torch.Size([32000, 5120]).
        size mismatch for model.layers.0.self_attn.k_proj.qzeros: copying a param with shape torch.Size([40, 640]) from checkpoint, the shape in current model is torch.Size([1, 640]).
        size mismatch for model.layers.0.self_attn.k_proj.scales: copying a param with shape torch.Size([40, 5120]) from checkpoint, the shape in current model is torch.Size([1, 5120]).
        size mismatch for model.layers.0.self_attn.o_proj.qzeros: copying a param with shape torch.Size([40, 640]) from checkpoint, the shape in current model is torch.Size([1, 640]).....`

**Comment by Gitterman69** [comment]
Check my link above - and get the safetensor format, that one works

**Comment by Kreevoz** [comment]
Yeah the files Gitterman linked to work really well. If you additionally name the folder something like `llama-13b-4bit-128g-vicuna` , you won't have to specify what model type it is since it'll figure that out by the folder name, then.

**Comment by ChobPT** [comment]
FYI, I spent soo much time with this and the model had safe tensor instead of safetensors extension....

**Comment by Gitterman69** [comment]
https://huggingface.co/anon8231489123/vicuna-13b-GPTQ-4bit-128g/tree/main => this model works flawless and offers superb quality!
