### ISSUE TITLE
Cuda out of memory

### ISSUE THREAD

**Issue by birdup000** [oobabooga/text-generation-webui#912]
### Describe the bug

Hello I'm trying to load Vicuna specifically "anon8231489123/vicuna-13b-GPTQ-4bit-128g" on my Nvidia RTX 2060 6gb model and it says 
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 6.00 GiB total capacity; 5.10 GiB already allocated; 0 bytes free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

I am unsure what to do.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

start webui
load model 
then shows error

### Screenshot

![image](https://user-images.githubusercontent.com/34012548/230709451-ff44c854-2da8-4b23-ab20-f65a536135d8.png)

### Logs

```shell
Starting the web UI...
Warning: --cai-chat is deprecated. Use --chat instead.

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
CUDA SETUP: CUDA runtime path found: C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 7.5
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
Loading anon8231489123_vicuna-13b-GPTQ-4bit-128g...
Loading model ...
C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\safetensors\torch.py:99: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  with safe_open(filename, framework="pt", device=device) as f:
C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\_utils.py:776: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  return self.fget.__get__(instance, owner)()
C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\storage.py:899: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  storage = cls(wrap_storage=untyped_storage)
Done.
Traceback (most recent call last):
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\text-generation-webui\modules\models.py", line 102, in load_model
    model = load_quantized(model_name)
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\text-generation-webui\modules\GPTQ_loader.py", line 153, in load_quantized
    model = model.to(torch.device('cuda:0'))
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\transformers\modeling_utils.py", line 1888, in to
    return super().to(*args, **kwargs)
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1145, in to
    return self._apply(convert)
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 797, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 844, in _apply
    self._buffers[key] = fn(buf)
  File "C:\Users\geckocakes\Downloads\oobabooga-windows\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 34.00 MiB (GPU 0; 6.00 GiB total capacity; 5.10 GiB already allocated; 0 bytes free; 5.29 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Press any key to continue . . .
```

### System Info

```shell
Asus Duel Evo OC Nvidia RTX 2060 6gb, Windows 10 64-bit 22H2
```

**Comment by catalpaaa** [comment]
try --pre-layer 20

**Comment by Crimsonfart** [comment]
Thanks, that's how it works! I have a GTX 3060TI 8Gb VRAM and with --pre_layer 20 i get 0.54 tokens/s and with 30 layers 1.06 tokens/s. GPU utilization is 55%. can you increase it or is that because the GPU has to wait for data from the RAM?

**Comment by greengeckowizard** [comment]
Thanks it worked! But I am also receiving the slow speed just like @Crimsonfart is experiencing.

**Comment by greengeckowizard** [comment]
![image](https://user-images.githubusercontent.com/34012548/230729556-d5d404fb-ff9d-46b9-bf45-d48efc6cec76.png)

**Comment by jllllll** [comment]
`--pre_layer` splits the model between VRAM and RAM. There is no avoiding slow speeds when doing this as the layers in RAM have to transfer data from RAM, into the CPU, and then into the GPU and all the way back. This massively slows down the model.

The more layers you have in VRAM, the faster your GPU will be able to run the model. This model, and others of similar size, has 40 layers in total. Each layer requires ~0.222 MiB of memory. With a 6gb GPU, 25 layers is pretty much the max that it can hold, though you will run out of memory if you run the model long enough. You generally need to leave ~1gb free for inferencing.

There are newer techniques to allow for better speeds and lower memory requirements, but they only really support Linux for now.

**Comment by EyeDeck** [comment]
If you can't load a full model into VRAM, there's a very good chance that CPU inference via llama.cpp would be faster on your machine.
https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models

**Comment by jllllll** [comment]
Absolutely, I can run 30b models at decent speed with that. Takes all of my 32gb of RAM to do it though.

Here is how to install the requirements for llama.cpp models in webui easily:

1. Download this archive here: https://github.com/abetlen/llama-cpp-python/suites/12105838837/artifacts/637822425
2. Extract `llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl` from it and place it next to `micromamba-cmd.bat`
3. Open `micromamba-cmd.bat` and enter this command: 
```
python -m pip install llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl
```
If not on Windows, there are Linux wheels in that archive as well, though it is better to compile llama-cpp-python yourself if you can.

**Comment by Dan00tz** [comment]
> 

For me it's not working. IDK if I'm doing it in a wrong way.
![image](https://user-images.githubusercontent.com/996996/230739728-56768dde-e1a6-490a-9adb-670c6c013112.png)

**Comment by EyeDeck** [comment]
It's an underscore for some reason: `--pre_layer`

**Comment by Reshaflame** [comment]
> try --pre-layer 20

where to put it?

**Comment by catalpaaa** [comment]
> > try --pre-layer 20
> 
> 
> 
> where to put it?

Next to where u place --cai-chat

**Comment by Crimsonfart** [comment]
> 

OMG now it works! I've already given up. When I followed these instructions: https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models it didn't work (possibly I was too stupid for it). Thanks for the help! As you said, for people like me who have an 8 GB VRAM GPU (0.5 tokens/s) Llama.cpp (~3 tokens/s 16GB RAM i5 11400F) is much faster.

**Comment by Crimsonfart** [comment]
> Absolutely, I can run 30b models at decent speed with that. Takes all of my 32gb of RAM to do it though. 13b models run just as fast, if not faster, than GPU 13b.
> 
> Here is how to install the requirements for llama.cpp models in webui easily:
> 
>     1. Download this archive here: https://github.com/abetlen/llama-cpp-python/suites/12105838837/artifacts/637822425
> 
>     2. Extract `llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl` from it and place it next to `micromamba-cmd.bat`
> 
>     3. Open `micromamba-cmd.bat` and enter this command:
> 
> 
> ```
> python -m pip install llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl
> ```
> 
> If not on Windows, there are Linux wheels in that archive as well, though it is better to compile llama-cpp-python yourself if you can.

OMG now it works! I've already given up. When I followed these instructions: https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models it didn't work (possibly I was too stupid for it). Thanks for the help! As you said, for people like me who have an 8 GB VRAM GPU (0.5 tokens/s) Llama.cpp (~3 tokens/s 16GB RAM i5 11400F) is much faster.

**Comment by Enferlain** [comment]
That actually worked for me as well, pogu. Although dunno why but I get stuck at x is typing... at 100% CPU util

**Comment by powercore2000** [comment]
> Absolutely, I can run 30b models at decent speed with that. Takes all of my 32gb of RAM to do it though. 13b models run just as fast, if not faster, than GPU 13b.
> 
> Here is how to install the requirements for llama.cpp models in webui easily:
> 
> 1. Download this archive here: https://github.com/abetlen/llama-cpp-python/suites/12105838837/artifacts/637822425
> 2. Extract `llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl` from it and place it next to `micromamba-cmd.bat`
> 3. Open `micromamba-cmd.bat` and enter this command:
> 
> ```
> python -m pip install llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl
> ```
> 
> If not on Windows, there are Linux wheels in that archive as well, though it is better to compile llama-cpp-python yourself if you can.

You sir rock, can confirm helps it work for me!

**Comment by BrachoAlex** [comment]
> > Absolutely, I can run 30b models at decent speed with that. Takes all of my 32gb of RAM to do it though. 13b models run just as fast, if not faster, than GPU 13b.
> > Here is how to install the requirements for llama.cpp models in webui easily:
> > 
> > 1. Download this archive here: https://github.com/abetlen/llama-cpp-python/suites/12105838837/artifacts/637822425
> > 2. Extract `llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl` from it and place it next to `micromamba-cmd.bat`
> > 3. Open `micromamba-cmd.bat` and enter this command:
> > 
> > ```
> > python -m pip install llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If not on Windows, there are Linux wheels in that archive as well, though it is better to compile llama-cpp-python yourself if you can.
> 
> You sir rock, can confirm helps it work for me!

Hmm, the file appears to be down for some reason.

**Comment by igorpichnenko** [comment]
> > Безусловно, я могу запускать модели 30b с приличной скоростью с этим. Для этого требуется все мои 32 ГБ оперативной памяти. модели 13b работают так же быстро, если не быстрее, чем GPU 13b.
> > Вот как установить требования для llama.cpp модели в webui легко:
> > ```
> > 1. Download this archive here: https://github.com/abetlen/llama-cpp-python/suites/12105838837/artifacts/637822425
> > 
> > 2. Extract `llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl` from it and place it next to `micromamba-cmd.bat`
> > 
> > 3. Open `micromamba-cmd.bat` and enter this command:
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > python -m pip install llama_cpp_python-0.1.26-cp310-cp310-win_amd64.whl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Если не в Windows, в этом архиве также есть диски Linux, хотя лучше скомпилировать llama-cpp-python самостоятельно, если вы можете.
> 
> БОЖЕ, теперь это работает! Я уже сдался. Когда я следовал этим инструкциям: [https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models ](https://github.com/oobabooga/text-generation-webui/wiki/llama.cpp-models) это не сработало (возможно, я был слишком глуп для этого). Спасибо за помощь! Как вы сказали, для таких людей, как я, у которых есть графический процессор VRAM объемом 8 ГБ (0,5 токена / с) Llama.cpp (~ 3 токена / с, 16 ГБ оперативной памяти i5 11400F) намного быстрее.

hello, tell me, please, how can this be used with vicuña?

**Comment by jllllll** [comment]
@igorpichnenko I use this model: https://huggingface.co/ShreyasBrill/Vicuna-13B/tree/main

**Comment by powercore2000** [comment]
@jllllll Just to check, what arguments did you run python server.py with?

**Comment by jllllll** [comment]
@powercore2000

ggml:
`--chat --model Vicuna-13B`

safetensors:
`--chat --model Vicuna-13B --wbits 4 --groupsize 128`

Both worked for me. It's worth noting that I have a 1080ti, which has enough VRAM to load the model in it's entirety. I have tested `--pre_layer` and it worked, but it's so slow that I never use it and just stick to models that I can fit in VRAM.

**Comment by powercore2000** [comment]
> @powercore2000
> 
> ggml: `--chat --model Vicuna-13B`
> 
> safetensors: `--chat --model Vicuna-13B --wbits 4 --groupsize 128`
> 
> Both worked for me. It's worth noting that I have a 1080ti, which has enough VRAM to load the model in it's entirety. I have tested `--pre_layer` and it worked, but it's so slow that I never use it and just stick to models that I can fit in VRAM or just use ggml.

Thanks for the info! I've been trying to load ggml models with oobabooga and the performance has been way lower than it should be (0.32 tokens/second) for a Ryzen 9 5900x. I was wondering if the issue was in my arguments.

**Comment by Enferlain** [comment]
@powercore2000 figured out why the speed is low? I had same issue, although on 3950x

**Comment by Crimsonfart** [comment]
> @powercore2000 figured out why the speed is low? I had same issue, although on 3950x

Use this and enjoy the speed ----> `call python server.py --auto-devices --chat --threads 10`
Make sure that you leave 2 or at least 1 thread free for the rest (win, browser ect.) in my case 10 because i have a i511400f 6 core 12 Threads CPU.

**Comment by Enferlain** [comment]
Tried it with --threads 30 and similar results. 

`Output generated in 36.01 seconds (0.19 tokens/s, 7 tokens, context 43)
`

Gonna set everything up again and also check if llamacpp is this slow too

**Comment by Enferlain** [comment]
Can't set up llamacpp, so can't test there. In koboldcpp it's a bit faster, but it has missing features compared to this webui, and before this update even the 30B was fast for me so not sure what happened.

**Comment by jllllll** [comment]
@Enferlain The memory listing there is wrong. For some reason, the program does not report it's RAM usage correctly to Task Manager. You have to look at the performance tab to see the actual RAM usage.

**Comment by powercore2000** [comment]
After doing that update, I am getting about 3 tokens/second now, still low, but a bit better

**Comment by Enferlain** [comment]
@powercore2000 changed it and now


```
Traceback (most recent call last):
  File "D:\textgen\oobabooga-windows\text-generation-webui\server.py", line 302, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\textgen\oobabooga-windows\text-generation-webui\modules\models.py", line 106, in load_model
    from modules.llamacpp_model import LlamaCppModel
  File "D:\textgen\oobabooga-windows\text-generation-webui\modules\llamacpp_model.py", line 3, in <module>
    import llamacpp
ModuleNotFoundError: No module named 'llamacpp'

```

**Comment by powercore2000** [comment]
> 3950x context size 1058 alpaca 13b lora merged
28 threads - 0.54 tokens/s
20 - 0.69
16 - 0.62
12 - 0.62
8 - 0.56

Those rates are still pretty low, but glad to hear it's working at least. I'm not sure what needs to be done to increase CPU efficiency to make it comparable to using normal llama.cpp however

**Comment by Enferlain** [comment]
Does it show for you anything related to the threads you set when launching the webui bat?

**Comment by TangentFoxy** [comment]
@jllllll You said:

> There are newer techniques to allow for better speeds and lower memory requirements, but they only really support Linux for now.

What are they, how can I find them? I'm running this on Ubuntu currently because it's what I happen to be running daily right now. It's been pretty difficult to get anything running when I'm new to this, especially because a lot of jargon is used without explanation for what it actually means (for example, I still have no idea what a wheel is or how to find/use them).

**Comment by luthis1124** [comment]
> @jllllll You said:
> 
> > There are newer techniques to allow for better speeds and lower memory requirements, but they only really support Linux for now.
> 
> What are they, how can I find them? I'm running this on Ubuntu currently because it's what I happen to be running daily right now. It's been pretty difficult to get anything running when I'm new to this, especially because a lot of jargon is used without explanation for what it actually means (for example, I still have no idea what a wheel is or how to find/use them).

I think you'll be happy with AItrepreneurs latest update:
https://www.youtube.com/watch?v=199h5XxUEOY

**Comment by TangentFoxy** [comment]
I did see that, but tbh I've left this space for the time being as it just seems way too unstable for me to get anything useful out of it. I intend to try again on Windows to see if it's more stable (I at least want to cross the threshold from freezing my computer to just crashing the program.. it's incredibly upsetting when it breaks everything instead of just itself).
