### ISSUE TITLE
quant_cuda and cuda not found even though cuda is found upon start

### ISSUE THREAD

**Issue by Lesani** [oobabooga/text-generation-webui#925]
### Describe the bug

![image](https://user-images.githubusercontent.com/5182104/230737030-c1786ea7-28c0-421b-a444-867db7d06481.png)

upon starting cuda seems to be found alreight
after model selection the UI starts fine but I get the "cuda extension not installed" error
when I try to generate, I get the traceback-quant_cuda error

I have executed the instructions here https://github.com/oobabooga/text-generation-webui/issues/795#issuecomment-1499830472:
https://github.com/oobabooga/text-generation-webui/wiki/LLaMA-model#step-1-install-gptq-for-llama

I have modified the config.json and tokenizer.config.json as suggested in comment:

![image](https://user-images.githubusercontent.com/5182104/230737139-7e0d3f73-1fd1-46e5-bb6b-f0254168d7ab.png)

I have tried reinstalling quant-cuda as per instructions by oobabooga here:
https://github.com/oobabooga/text-generation-webui/issues/716#issuecomment-1493219583

nothing lead to a change in the behaviour
the result is the same with model 4 (vicuna)

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

call python server.py --auto-devices --wbits 4 --groupsize 128 --chat

### Logs

```shell
´
Starting the web UI...

===================================BUG REPORT===================================Welcome to bitsandbytes. For bug reports, please submit your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================CUDA SETUP: CUDA runtime path found: F:\LLM\windows\oobabooga-old\installer_files\env\bin\cudart64_110.dll
CUDA SETUP: Highest compute capability among GPUs detected: 8.9
CUDA SETUP: Detected CUDA version 117
CUDA SETUP: Loading binary F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cuda117.dll...
The following models are available:

1. gpt4-x-alpaca-13b-native-4bit-128g
2. opt-6.7b
3. pygmalion-6b
4. vicuna-13b-GPTQ-4bit-128g

Which one do you want to load? 1-4

1

Loading gpt4-x-alpaca-13b-native-4bit-128g...
CUDA extension not installed.
Loading model ...
Done.
Loaded the model in 23.61 seconds.
Loading the extension "gallery"... Ok.
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "F:\LLM\windows\oobabooga-old\text-generation-webui\modules\callbacks.py", line 66, in gentask
    ret = self.mfunc(callback=_callback, **self.kwargs)
  File "F:\LLM\windows\oobabooga-old\text-generation-webui\modules\text_generation.py", line 224, in generate_with_callback
    shared.model.generate(**kwargs)
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 1485, in generate
    return self.sample(
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\transformers\generation\utils.py", line 2524, in sample
    outputs = self(
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 687, in forward
    outputs = self.model(
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 577, in forward
    layer_outputs = decoder_layer(
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 292, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\transformers\models\llama\modeling_llama.py", line 196, in forward
    query_states = self.q_proj(hidden_states).view(bsz, q_len, self.num_heads, self.head_dim).transpose(1, 2)
  File "F:\LLM\windows\oobabooga-old\installer_files\env\lib\site-packages\torch\nn\modules\module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "F:\LLM\windows\oobabooga-old\text-generation-webui\repositories\GPTQ-for-LLaMa\quant.py", line 426, in forward
    quant_cuda.vecquant4matmul(x, self.qweight, y, self.scales, self.qzeros, self.groupsize)
NameError: name 'quant_cuda' is not defined
Output generated in 2.27 seconds (0.00 tokens/s, 0 tokens, context 36)
´
```

### System Info

```shell
W10 RTX4090
```

**Comment by Lesani** [comment]
created a new issue because I haven'T found in all the threads I searched anyone who had done all the steps and actually has cuda being recognized without issue before loading a model

**Comment by catalpaaa** [comment]
It still says CUDA extension not installed in your log, that's why it can't properly import quant_cuda.

Make sure you have run the setup_cuda.py properly, maybe give a log

**Comment by Lesani** [comment]
I did a complete reinstall of the text-generation-webui and it works there.

the setup_cuda.py ran through with a success message at the end before.
